// Code generated by ent, DO NOT EDIT.

package initiative

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the initiative type in the database.
	Label = "initiative"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProduct holds the string denoting the product field in the database.
	FieldProduct = "product"
	// FieldReferenceNum holds the string denoting the reference_num field in the database.
	FieldReferenceNum = "reference_num"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldEffort holds the string denoting the effort field in the database.
	FieldEffort = "effort"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// Table holds the table name of the initiative in the database.
	Table = "initiatives"
)

// Columns holds all SQL columns for initiative fields.
var Columns = []string{
	FieldID,
	FieldProduct,
	FieldReferenceNum,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldValue,
	FieldEffort,
	FieldProgress,
	FieldStartDate,
	FieldEndDate,
	FieldURL,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Initiative queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProduct orders the results by the product field.
func ByProduct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProduct, opts...).ToFunc()
}

// ByReferenceNum orders the results by the reference_num field.
func ByReferenceNum(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceNum, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByEffort orders the results by the effort field.
func ByEffort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffort, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByEndDate orders the results by the end_date field.
func ByEndDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndDate, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
