// Code generated by ent, DO NOT EDIT.

package requirement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldID, id))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldProduct, v))
}

// FeatureID applies equality check predicate on the "feature_id" field. It's identical to FeatureIDEQ.
func FeatureID(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldFeatureID, v))
}

// ReferenceNum applies equality check predicate on the "reference_num" field. It's identical to ReferenceNumEQ.
func ReferenceNum(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldReferenceNum, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldStatus, v))
}

// AssignedTo applies equality check predicate on the "assigned_to" field. It's identical to AssignedToEQ.
func AssignedTo(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldAssignedTo, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldPosition, v))
}

// OriginalEstimate applies equality check predicate on the "original_estimate" field. It's identical to OriginalEstimateEQ.
func OriginalEstimate(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldOriginalEstimate, v))
}

// RemainingEstimate applies equality check predicate on the "remaining_estimate" field. It's identical to RemainingEstimateEQ.
func RemainingEstimate(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldRemainingEstimate, v))
}

// WorkDone applies equality check predicate on the "work_done" field. It's identical to WorkDoneEQ.
func WorkDone(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldWorkDone, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldProduct, v))
}

// FeatureIDEQ applies the EQ predicate on the "feature_id" field.
func FeatureIDEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldFeatureID, v))
}

// FeatureIDNEQ applies the NEQ predicate on the "feature_id" field.
func FeatureIDNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldFeatureID, v))
}

// FeatureIDIn applies the In predicate on the "feature_id" field.
func FeatureIDIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldFeatureID, vs...))
}

// FeatureIDNotIn applies the NotIn predicate on the "feature_id" field.
func FeatureIDNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldFeatureID, vs...))
}

// FeatureIDGT applies the GT predicate on the "feature_id" field.
func FeatureIDGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldFeatureID, v))
}

// FeatureIDGTE applies the GTE predicate on the "feature_id" field.
func FeatureIDGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldFeatureID, v))
}

// FeatureIDLT applies the LT predicate on the "feature_id" field.
func FeatureIDLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldFeatureID, v))
}

// FeatureIDLTE applies the LTE predicate on the "feature_id" field.
func FeatureIDLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldFeatureID, v))
}

// FeatureIDContains applies the Contains predicate on the "feature_id" field.
func FeatureIDContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldFeatureID, v))
}

// FeatureIDHasPrefix applies the HasPrefix predicate on the "feature_id" field.
func FeatureIDHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldFeatureID, v))
}

// FeatureIDHasSuffix applies the HasSuffix predicate on the "feature_id" field.
func FeatureIDHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldFeatureID, v))
}

// FeatureIDIsNil applies the IsNil predicate on the "feature_id" field.
func FeatureIDIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldFeatureID))
}

// FeatureIDNotNil applies the NotNil predicate on the "feature_id" field.
func FeatureIDNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldFeatureID))
}

// FeatureIDEqualFold applies the EqualFold predicate on the "feature_id" field.
func FeatureIDEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldFeatureID, v))
}

// FeatureIDContainsFold applies the ContainsFold predicate on the "feature_id" field.
func FeatureIDContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldFeatureID, v))
}

// ReferenceNumEQ applies the EQ predicate on the "reference_num" field.
func ReferenceNumEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldReferenceNum, v))
}

// ReferenceNumNEQ applies the NEQ predicate on the "reference_num" field.
func ReferenceNumNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldReferenceNum, v))
}

// ReferenceNumIn applies the In predicate on the "reference_num" field.
func ReferenceNumIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldReferenceNum, vs...))
}

// ReferenceNumNotIn applies the NotIn predicate on the "reference_num" field.
func ReferenceNumNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldReferenceNum, vs...))
}

// ReferenceNumGT applies the GT predicate on the "reference_num" field.
func ReferenceNumGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldReferenceNum, v))
}

// ReferenceNumGTE applies the GTE predicate on the "reference_num" field.
func ReferenceNumGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldReferenceNum, v))
}

// ReferenceNumLT applies the LT predicate on the "reference_num" field.
func ReferenceNumLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldReferenceNum, v))
}

// ReferenceNumLTE applies the LTE predicate on the "reference_num" field.
func ReferenceNumLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldReferenceNum, v))
}

// ReferenceNumContains applies the Contains predicate on the "reference_num" field.
func ReferenceNumContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldReferenceNum, v))
}

// ReferenceNumHasPrefix applies the HasPrefix predicate on the "reference_num" field.
func ReferenceNumHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldReferenceNum, v))
}

// ReferenceNumHasSuffix applies the HasSuffix predicate on the "reference_num" field.
func ReferenceNumHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldReferenceNum, v))
}

// ReferenceNumIsNil applies the IsNil predicate on the "reference_num" field.
func ReferenceNumIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldReferenceNum))
}

// ReferenceNumNotNil applies the NotNil predicate on the "reference_num" field.
func ReferenceNumNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldReferenceNum))
}

// ReferenceNumEqualFold applies the EqualFold predicate on the "reference_num" field.
func ReferenceNumEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldReferenceNum, v))
}

// ReferenceNumContainsFold applies the ContainsFold predicate on the "reference_num" field.
func ReferenceNumContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldReferenceNum, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldStatus, v))
}

// AssignedToEQ applies the EQ predicate on the "assigned_to" field.
func AssignedToEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldAssignedTo, v))
}

// AssignedToNEQ applies the NEQ predicate on the "assigned_to" field.
func AssignedToNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldAssignedTo, v))
}

// AssignedToIn applies the In predicate on the "assigned_to" field.
func AssignedToIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldAssignedTo, vs...))
}

// AssignedToNotIn applies the NotIn predicate on the "assigned_to" field.
func AssignedToNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldAssignedTo, vs...))
}

// AssignedToGT applies the GT predicate on the "assigned_to" field.
func AssignedToGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldAssignedTo, v))
}

// AssignedToGTE applies the GTE predicate on the "assigned_to" field.
func AssignedToGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldAssignedTo, v))
}

// AssignedToLT applies the LT predicate on the "assigned_to" field.
func AssignedToLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldAssignedTo, v))
}

// AssignedToLTE applies the LTE predicate on the "assigned_to" field.
func AssignedToLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldAssignedTo, v))
}

// AssignedToContains applies the Contains predicate on the "assigned_to" field.
func AssignedToContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldAssignedTo, v))
}

// AssignedToHasPrefix applies the HasPrefix predicate on the "assigned_to" field.
func AssignedToHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldAssignedTo, v))
}

// AssignedToHasSuffix applies the HasSuffix predicate on the "assigned_to" field.
func AssignedToHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldAssignedTo, v))
}

// AssignedToIsNil applies the IsNil predicate on the "assigned_to" field.
func AssignedToIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldAssignedTo))
}

// AssignedToNotNil applies the NotNil predicate on the "assigned_to" field.
func AssignedToNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldAssignedTo))
}

// AssignedToEqualFold applies the EqualFold predicate on the "assigned_to" field.
func AssignedToEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldAssignedTo, v))
}

// AssignedToContainsFold applies the ContainsFold predicate on the "assigned_to" field.
func AssignedToContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldAssignedTo, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldPosition, v))
}

// PositionIsNil applies the IsNil predicate on the "position" field.
func PositionIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldPosition))
}

// PositionNotNil applies the NotNil predicate on the "position" field.
func PositionNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldPosition))
}

// OriginalEstimateEQ applies the EQ predicate on the "original_estimate" field.
func OriginalEstimateEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldOriginalEstimate, v))
}

// OriginalEstimateNEQ applies the NEQ predicate on the "original_estimate" field.
func OriginalEstimateNEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldOriginalEstimate, v))
}

// OriginalEstimateIn applies the In predicate on the "original_estimate" field.
func OriginalEstimateIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldOriginalEstimate, vs...))
}

// OriginalEstimateNotIn applies the NotIn predicate on the "original_estimate" field.
func OriginalEstimateNotIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldOriginalEstimate, vs...))
}

// OriginalEstimateGT applies the GT predicate on the "original_estimate" field.
func OriginalEstimateGT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldOriginalEstimate, v))
}

// OriginalEstimateGTE applies the GTE predicate on the "original_estimate" field.
func OriginalEstimateGTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldOriginalEstimate, v))
}

// OriginalEstimateLT applies the LT predicate on the "original_estimate" field.
func OriginalEstimateLT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldOriginalEstimate, v))
}

// OriginalEstimateLTE applies the LTE predicate on the "original_estimate" field.
func OriginalEstimateLTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldOriginalEstimate, v))
}

// OriginalEstimateIsNil applies the IsNil predicate on the "original_estimate" field.
func OriginalEstimateIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldOriginalEstimate))
}

// OriginalEstimateNotNil applies the NotNil predicate on the "original_estimate" field.
func OriginalEstimateNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldOriginalEstimate))
}

// RemainingEstimateEQ applies the EQ predicate on the "remaining_estimate" field.
func RemainingEstimateEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldRemainingEstimate, v))
}

// RemainingEstimateNEQ applies the NEQ predicate on the "remaining_estimate" field.
func RemainingEstimateNEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldRemainingEstimate, v))
}

// RemainingEstimateIn applies the In predicate on the "remaining_estimate" field.
func RemainingEstimateIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldRemainingEstimate, vs...))
}

// RemainingEstimateNotIn applies the NotIn predicate on the "remaining_estimate" field.
func RemainingEstimateNotIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldRemainingEstimate, vs...))
}

// RemainingEstimateGT applies the GT predicate on the "remaining_estimate" field.
func RemainingEstimateGT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldRemainingEstimate, v))
}

// RemainingEstimateGTE applies the GTE predicate on the "remaining_estimate" field.
func RemainingEstimateGTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldRemainingEstimate, v))
}

// RemainingEstimateLT applies the LT predicate on the "remaining_estimate" field.
func RemainingEstimateLT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldRemainingEstimate, v))
}

// RemainingEstimateLTE applies the LTE predicate on the "remaining_estimate" field.
func RemainingEstimateLTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldRemainingEstimate, v))
}

// RemainingEstimateIsNil applies the IsNil predicate on the "remaining_estimate" field.
func RemainingEstimateIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldRemainingEstimate))
}

// RemainingEstimateNotNil applies the NotNil predicate on the "remaining_estimate" field.
func RemainingEstimateNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldRemainingEstimate))
}

// WorkDoneEQ applies the EQ predicate on the "work_done" field.
func WorkDoneEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldWorkDone, v))
}

// WorkDoneNEQ applies the NEQ predicate on the "work_done" field.
func WorkDoneNEQ(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldWorkDone, v))
}

// WorkDoneIn applies the In predicate on the "work_done" field.
func WorkDoneIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldWorkDone, vs...))
}

// WorkDoneNotIn applies the NotIn predicate on the "work_done" field.
func WorkDoneNotIn(vs ...float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldWorkDone, vs...))
}

// WorkDoneGT applies the GT predicate on the "work_done" field.
func WorkDoneGT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldWorkDone, v))
}

// WorkDoneGTE applies the GTE predicate on the "work_done" field.
func WorkDoneGTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldWorkDone, v))
}

// WorkDoneLT applies the LT predicate on the "work_done" field.
func WorkDoneLT(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldWorkDone, v))
}

// WorkDoneLTE applies the LTE predicate on the "work_done" field.
func WorkDoneLTE(v float64) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldWorkDone, v))
}

// WorkDoneIsNil applies the IsNil predicate on the "work_done" field.
func WorkDoneIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldWorkDone))
}

// WorkDoneNotNil applies the NotNil predicate on the "work_done" field.
func WorkDoneNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldWorkDone))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Requirement {
	return predicate.Requirement(sql.FieldContainsFold(FieldURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Requirement {
	return predicate.Requirement(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldUpdatedAt))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Requirement {
	return predicate.Requirement(sql.FieldNotNull(FieldData))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Requirement) predicate.Requirement {
	return predicate.Requirement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Requirement) predicate.Requirement {
	return predicate.Requirement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Requirement) predicate.Requirement {
	return predicate.Requirement(sql.NotPredicates(p))
}
