// Code generated by ent, DO NOT EDIT.

package feature

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldID, id))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldProduct, v))
}

// ReferenceNum applies equality check predicate on the "reference_num" field. It's identical to ReferenceNumEQ.
func ReferenceNum(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReferenceNum, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldStatus, v))
}

// AssignedTo applies equality check predicate on the "assigned_to" field. It's identical to AssignedToEQ.
func AssignedTo(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldAssignedTo, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldStartDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDueDate, v))
}

// Release applies equality check predicate on the "release" field. It's identical to ReleaseEQ.
func Release(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldRelease, v))
}

// ReleaseID applies equality check predicate on the "release_id" field. It's identical to ReleaseIDEQ.
func ReleaseID(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReleaseID, v))
}

// ReleaseReferenceNum applies equality check predicate on the "release_reference_num" field. It's identical to ReleaseReferenceNumEQ.
func ReleaseReferenceNum(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReleaseReferenceNum, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldTags, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldProduct, v))
}

// ReferenceNumEQ applies the EQ predicate on the "reference_num" field.
func ReferenceNumEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReferenceNum, v))
}

// ReferenceNumNEQ applies the NEQ predicate on the "reference_num" field.
func ReferenceNumNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldReferenceNum, v))
}

// ReferenceNumIn applies the In predicate on the "reference_num" field.
func ReferenceNumIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldReferenceNum, vs...))
}

// ReferenceNumNotIn applies the NotIn predicate on the "reference_num" field.
func ReferenceNumNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldReferenceNum, vs...))
}

// ReferenceNumGT applies the GT predicate on the "reference_num" field.
func ReferenceNumGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldReferenceNum, v))
}

// ReferenceNumGTE applies the GTE predicate on the "reference_num" field.
func ReferenceNumGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldReferenceNum, v))
}

// ReferenceNumLT applies the LT predicate on the "reference_num" field.
func ReferenceNumLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldReferenceNum, v))
}

// ReferenceNumLTE applies the LTE predicate on the "reference_num" field.
func ReferenceNumLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldReferenceNum, v))
}

// ReferenceNumContains applies the Contains predicate on the "reference_num" field.
func ReferenceNumContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldReferenceNum, v))
}

// ReferenceNumHasPrefix applies the HasPrefix predicate on the "reference_num" field.
func ReferenceNumHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldReferenceNum, v))
}

// ReferenceNumHasSuffix applies the HasSuffix predicate on the "reference_num" field.
func ReferenceNumHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldReferenceNum, v))
}

// ReferenceNumIsNil applies the IsNil predicate on the "reference_num" field.
func ReferenceNumIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldReferenceNum))
}

// ReferenceNumNotNil applies the NotNil predicate on the "reference_num" field.
func ReferenceNumNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldReferenceNum))
}

// ReferenceNumEqualFold applies the EqualFold predicate on the "reference_num" field.
func ReferenceNumEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldReferenceNum, v))
}

// ReferenceNumContainsFold applies the ContainsFold predicate on the "reference_num" field.
func ReferenceNumContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldReferenceNum, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldStatus, v))
}

// AssignedToEQ applies the EQ predicate on the "assigned_to" field.
func AssignedToEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldAssignedTo, v))
}

// AssignedToNEQ applies the NEQ predicate on the "assigned_to" field.
func AssignedToNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldAssignedTo, v))
}

// AssignedToIn applies the In predicate on the "assigned_to" field.
func AssignedToIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldAssignedTo, vs...))
}

// AssignedToNotIn applies the NotIn predicate on the "assigned_to" field.
func AssignedToNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldAssignedTo, vs...))
}

// AssignedToGT applies the GT predicate on the "assigned_to" field.
func AssignedToGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldAssignedTo, v))
}

// AssignedToGTE applies the GTE predicate on the "assigned_to" field.
func AssignedToGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldAssignedTo, v))
}

// AssignedToLT applies the LT predicate on the "assigned_to" field.
func AssignedToLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldAssignedTo, v))
}

// AssignedToLTE applies the LTE predicate on the "assigned_to" field.
func AssignedToLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldAssignedTo, v))
}

// AssignedToContains applies the Contains predicate on the "assigned_to" field.
func AssignedToContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldAssignedTo, v))
}

// AssignedToHasPrefix applies the HasPrefix predicate on the "assigned_to" field.
func AssignedToHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldAssignedTo, v))
}

// AssignedToHasSuffix applies the HasSuffix predicate on the "assigned_to" field.
func AssignedToHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldAssignedTo, v))
}

// AssignedToIsNil applies the IsNil predicate on the "assigned_to" field.
func AssignedToIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldAssignedTo))
}

// AssignedToNotNil applies the NotNil predicate on the "assigned_to" field.
func AssignedToNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldAssignedTo))
}

// AssignedToEqualFold applies the EqualFold predicate on the "assigned_to" field.
func AssignedToEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldAssignedTo, v))
}

// AssignedToContainsFold applies the ContainsFold predicate on the "assigned_to" field.
func AssignedToContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldAssignedTo, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldStartDate, v))
}

// StartDateContains applies the Contains predicate on the "start_date" field.
func StartDateContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldStartDate, v))
}

// StartDateHasPrefix applies the HasPrefix predicate on the "start_date" field.
func StartDateHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldStartDate, v))
}

// StartDateHasSuffix applies the HasSuffix predicate on the "start_date" field.
func StartDateHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldStartDate))
}

// StartDateEqualFold applies the EqualFold predicate on the "start_date" field.
func StartDateEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldStartDate, v))
}

// StartDateContainsFold applies the ContainsFold predicate on the "start_date" field.
func StartDateContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldStartDate, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldDueDate, v))
}

// DueDateContains applies the Contains predicate on the "due_date" field.
func DueDateContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldDueDate, v))
}

// DueDateHasPrefix applies the HasPrefix predicate on the "due_date" field.
func DueDateHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldDueDate, v))
}

// DueDateHasSuffix applies the HasSuffix predicate on the "due_date" field.
func DueDateHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDueDate))
}

// DueDateEqualFold applies the EqualFold predicate on the "due_date" field.
func DueDateEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldDueDate, v))
}

// DueDateContainsFold applies the ContainsFold predicate on the "due_date" field.
func DueDateContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldDueDate, v))
}

// ReleaseEQ applies the EQ predicate on the "release" field.
func ReleaseEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldRelease, v))
}

// ReleaseNEQ applies the NEQ predicate on the "release" field.
func ReleaseNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldRelease, v))
}

// ReleaseIn applies the In predicate on the "release" field.
func ReleaseIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldRelease, vs...))
}

// ReleaseNotIn applies the NotIn predicate on the "release" field.
func ReleaseNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldRelease, vs...))
}

// ReleaseGT applies the GT predicate on the "release" field.
func ReleaseGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldRelease, v))
}

// ReleaseGTE applies the GTE predicate on the "release" field.
func ReleaseGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldRelease, v))
}

// ReleaseLT applies the LT predicate on the "release" field.
func ReleaseLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldRelease, v))
}

// ReleaseLTE applies the LTE predicate on the "release" field.
func ReleaseLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldRelease, v))
}

// ReleaseContains applies the Contains predicate on the "release" field.
func ReleaseContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldRelease, v))
}

// ReleaseHasPrefix applies the HasPrefix predicate on the "release" field.
func ReleaseHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldRelease, v))
}

// ReleaseHasSuffix applies the HasSuffix predicate on the "release" field.
func ReleaseHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldRelease, v))
}

// ReleaseIsNil applies the IsNil predicate on the "release" field.
func ReleaseIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldRelease))
}

// ReleaseNotNil applies the NotNil predicate on the "release" field.
func ReleaseNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldRelease))
}

// ReleaseEqualFold applies the EqualFold predicate on the "release" field.
func ReleaseEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldRelease, v))
}

// ReleaseContainsFold applies the ContainsFold predicate on the "release" field.
func ReleaseContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldRelease, v))
}

// ReleaseIDEQ applies the EQ predicate on the "release_id" field.
func ReleaseIDEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReleaseID, v))
}

// ReleaseIDNEQ applies the NEQ predicate on the "release_id" field.
func ReleaseIDNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldReleaseID, v))
}

// ReleaseIDIn applies the In predicate on the "release_id" field.
func ReleaseIDIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldReleaseID, vs...))
}

// ReleaseIDNotIn applies the NotIn predicate on the "release_id" field.
func ReleaseIDNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldReleaseID, vs...))
}

// ReleaseIDGT applies the GT predicate on the "release_id" field.
func ReleaseIDGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldReleaseID, v))
}

// ReleaseIDGTE applies the GTE predicate on the "release_id" field.
func ReleaseIDGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldReleaseID, v))
}

// ReleaseIDLT applies the LT predicate on the "release_id" field.
func ReleaseIDLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldReleaseID, v))
}

// ReleaseIDLTE applies the LTE predicate on the "release_id" field.
func ReleaseIDLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldReleaseID, v))
}

// ReleaseIDContains applies the Contains predicate on the "release_id" field.
func ReleaseIDContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldReleaseID, v))
}

// ReleaseIDHasPrefix applies the HasPrefix predicate on the "release_id" field.
func ReleaseIDHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldReleaseID, v))
}

// ReleaseIDHasSuffix applies the HasSuffix predicate on the "release_id" field.
func ReleaseIDHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldReleaseID, v))
}

// ReleaseIDIsNil applies the IsNil predicate on the "release_id" field.
func ReleaseIDIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldReleaseID))
}

// ReleaseIDNotNil applies the NotNil predicate on the "release_id" field.
func ReleaseIDNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldReleaseID))
}

// ReleaseIDEqualFold applies the EqualFold predicate on the "release_id" field.
func ReleaseIDEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldReleaseID, v))
}

// ReleaseIDContainsFold applies the ContainsFold predicate on the "release_id" field.
func ReleaseIDContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldReleaseID, v))
}

// ReleaseReferenceNumEQ applies the EQ predicate on the "release_reference_num" field.
func ReleaseReferenceNumEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumNEQ applies the NEQ predicate on the "release_reference_num" field.
func ReleaseReferenceNumNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumIn applies the In predicate on the "release_reference_num" field.
func ReleaseReferenceNumIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldReleaseReferenceNum, vs...))
}

// ReleaseReferenceNumNotIn applies the NotIn predicate on the "release_reference_num" field.
func ReleaseReferenceNumNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldReleaseReferenceNum, vs...))
}

// ReleaseReferenceNumGT applies the GT predicate on the "release_reference_num" field.
func ReleaseReferenceNumGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumGTE applies the GTE predicate on the "release_reference_num" field.
func ReleaseReferenceNumGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumLT applies the LT predicate on the "release_reference_num" field.
func ReleaseReferenceNumLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumLTE applies the LTE predicate on the "release_reference_num" field.
func ReleaseReferenceNumLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumContains applies the Contains predicate on the "release_reference_num" field.
func ReleaseReferenceNumContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumHasPrefix applies the HasPrefix predicate on the "release_reference_num" field.
func ReleaseReferenceNumHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumHasSuffix applies the HasSuffix predicate on the "release_reference_num" field.
func ReleaseReferenceNumHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumIsNil applies the IsNil predicate on the "release_reference_num" field.
func ReleaseReferenceNumIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldReleaseReferenceNum))
}

// ReleaseReferenceNumNotNil applies the NotNil predicate on the "release_reference_num" field.
func ReleaseReferenceNumNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldReleaseReferenceNum))
}

// ReleaseReferenceNumEqualFold applies the EqualFold predicate on the "release_reference_num" field.
func ReleaseReferenceNumEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldReleaseReferenceNum, v))
}

// ReleaseReferenceNumContainsFold applies the ContainsFold predicate on the "release_reference_num" field.
func ReleaseReferenceNumContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldReleaseReferenceNum, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldTags, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldUpdatedAt))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldData))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.NotPredicates(p))
}
