// Code generated by ent, DO NOT EDIT.

package savedfilter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldName, v))
}

// Aql applies equality check predicate on the "aql" field. It's identical to AqlEQ.
func Aql(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldAql, v))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldProduct, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldDescription, v))
}

// IsFavorite applies equality check predicate on the "is_favorite" field. It's identical to IsFavoriteEQ.
func IsFavorite(v bool) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldIsFavorite, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContainsFold(FieldName, v))
}

// AqlEQ applies the EQ predicate on the "aql" field.
func AqlEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldAql, v))
}

// AqlNEQ applies the NEQ predicate on the "aql" field.
func AqlNEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldAql, v))
}

// AqlIn applies the In predicate on the "aql" field.
func AqlIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldAql, vs...))
}

// AqlNotIn applies the NotIn predicate on the "aql" field.
func AqlNotIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldAql, vs...))
}

// AqlGT applies the GT predicate on the "aql" field.
func AqlGT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldAql, v))
}

// AqlGTE applies the GTE predicate on the "aql" field.
func AqlGTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldAql, v))
}

// AqlLT applies the LT predicate on the "aql" field.
func AqlLT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldAql, v))
}

// AqlLTE applies the LTE predicate on the "aql" field.
func AqlLTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldAql, v))
}

// AqlContains applies the Contains predicate on the "aql" field.
func AqlContains(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContains(FieldAql, v))
}

// AqlHasPrefix applies the HasPrefix predicate on the "aql" field.
func AqlHasPrefix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasPrefix(FieldAql, v))
}

// AqlHasSuffix applies the HasSuffix predicate on the "aql" field.
func AqlHasSuffix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasSuffix(FieldAql, v))
}

// AqlEqualFold applies the EqualFold predicate on the "aql" field.
func AqlEqualFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEqualFold(FieldAql, v))
}

// AqlContainsFold applies the ContainsFold predicate on the "aql" field.
func AqlContainsFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContainsFold(FieldAql, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductIsNil applies the IsNil predicate on the "product" field.
func ProductIsNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIsNull(FieldProduct))
}

// ProductNotNil applies the NotNil predicate on the "product" field.
func ProductNotNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotNull(FieldProduct))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContainsFold(FieldProduct, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldContainsFold(FieldDescription, v))
}

// IsFavoriteEQ applies the EQ predicate on the "is_favorite" field.
func IsFavoriteEQ(v bool) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldIsFavorite, v))
}

// IsFavoriteNEQ applies the NEQ predicate on the "is_favorite" field.
func IsFavoriteNEQ(v bool) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldIsFavorite, v))
}

// IsFavoriteIsNil applies the IsNil predicate on the "is_favorite" field.
func IsFavoriteIsNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIsNull(FieldIsFavorite))
}

// IsFavoriteNotNil applies the NotNil predicate on the "is_favorite" field.
func IsFavoriteNotNil() predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotNull(FieldIsFavorite))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SavedFilter {
	return predicate.SavedFilter(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SavedFilter) predicate.SavedFilter {
	return predicate.SavedFilter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SavedFilter) predicate.SavedFilter {
	return predicate.SavedFilter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SavedFilter) predicate.SavedFilter {
	return predicate.SavedFilter(sql.NotPredicates(p))
}
