// Code generated by ent, DO NOT EDIT.

package goal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldID, id))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldProduct, v))
}

// ReferenceNum applies equality check predicate on the "reference_num" field. It's identical to ReferenceNumEQ.
func ReferenceNum(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldReferenceNum, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStatus, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldProgress, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStartDate, v))
}

// EndDate applies equality check predicate on the "end_date" field. It's identical to EndDateEQ.
func EndDate(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldEndDate, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldProduct, v))
}

// ReferenceNumEQ applies the EQ predicate on the "reference_num" field.
func ReferenceNumEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldReferenceNum, v))
}

// ReferenceNumNEQ applies the NEQ predicate on the "reference_num" field.
func ReferenceNumNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldReferenceNum, v))
}

// ReferenceNumIn applies the In predicate on the "reference_num" field.
func ReferenceNumIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldReferenceNum, vs...))
}

// ReferenceNumNotIn applies the NotIn predicate on the "reference_num" field.
func ReferenceNumNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldReferenceNum, vs...))
}

// ReferenceNumGT applies the GT predicate on the "reference_num" field.
func ReferenceNumGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldReferenceNum, v))
}

// ReferenceNumGTE applies the GTE predicate on the "reference_num" field.
func ReferenceNumGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldReferenceNum, v))
}

// ReferenceNumLT applies the LT predicate on the "reference_num" field.
func ReferenceNumLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldReferenceNum, v))
}

// ReferenceNumLTE applies the LTE predicate on the "reference_num" field.
func ReferenceNumLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldReferenceNum, v))
}

// ReferenceNumContains applies the Contains predicate on the "reference_num" field.
func ReferenceNumContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldReferenceNum, v))
}

// ReferenceNumHasPrefix applies the HasPrefix predicate on the "reference_num" field.
func ReferenceNumHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldReferenceNum, v))
}

// ReferenceNumHasSuffix applies the HasSuffix predicate on the "reference_num" field.
func ReferenceNumHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldReferenceNum, v))
}

// ReferenceNumIsNil applies the IsNil predicate on the "reference_num" field.
func ReferenceNumIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldReferenceNum))
}

// ReferenceNumNotNil applies the NotNil predicate on the "reference_num" field.
func ReferenceNumNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldReferenceNum))
}

// ReferenceNumEqualFold applies the EqualFold predicate on the "reference_num" field.
func ReferenceNumEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldReferenceNum, v))
}

// ReferenceNumContainsFold applies the ContainsFold predicate on the "reference_num" field.
func ReferenceNumContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldReferenceNum, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldStatus))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldStatus, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...float64) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...float64) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v float64) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldProgress, v))
}

// ProgressIsNil applies the IsNil predicate on the "progress" field.
func ProgressIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldProgress))
}

// ProgressNotNil applies the NotNil predicate on the "progress" field.
func ProgressNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldProgress))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldStartDate, v))
}

// StartDateContains applies the Contains predicate on the "start_date" field.
func StartDateContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldStartDate, v))
}

// StartDateHasPrefix applies the HasPrefix predicate on the "start_date" field.
func StartDateHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldStartDate, v))
}

// StartDateHasSuffix applies the HasSuffix predicate on the "start_date" field.
func StartDateHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldStartDate))
}

// StartDateEqualFold applies the EqualFold predicate on the "start_date" field.
func StartDateEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldStartDate, v))
}

// StartDateContainsFold applies the ContainsFold predicate on the "start_date" field.
func StartDateContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldStartDate, v))
}

// EndDateEQ applies the EQ predicate on the "end_date" field.
func EndDateEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldEndDate, v))
}

// EndDateNEQ applies the NEQ predicate on the "end_date" field.
func EndDateNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldEndDate, v))
}

// EndDateIn applies the In predicate on the "end_date" field.
func EndDateIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldEndDate, vs...))
}

// EndDateNotIn applies the NotIn predicate on the "end_date" field.
func EndDateNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldEndDate, vs...))
}

// EndDateGT applies the GT predicate on the "end_date" field.
func EndDateGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldEndDate, v))
}

// EndDateGTE applies the GTE predicate on the "end_date" field.
func EndDateGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldEndDate, v))
}

// EndDateLT applies the LT predicate on the "end_date" field.
func EndDateLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldEndDate, v))
}

// EndDateLTE applies the LTE predicate on the "end_date" field.
func EndDateLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldEndDate, v))
}

// EndDateContains applies the Contains predicate on the "end_date" field.
func EndDateContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldEndDate, v))
}

// EndDateHasPrefix applies the HasPrefix predicate on the "end_date" field.
func EndDateHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldEndDate, v))
}

// EndDateHasSuffix applies the HasSuffix predicate on the "end_date" field.
func EndDateHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldEndDate, v))
}

// EndDateIsNil applies the IsNil predicate on the "end_date" field.
func EndDateIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldEndDate))
}

// EndDateNotNil applies the NotNil predicate on the "end_date" field.
func EndDateNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldEndDate))
}

// EndDateEqualFold applies the EqualFold predicate on the "end_date" field.
func EndDateEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldEndDate, v))
}

// EndDateContainsFold applies the ContainsFold predicate on the "end_date" field.
func EndDateContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldEndDate, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldUpdatedAt))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldData))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.NotPredicates(p))
}
