// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/comment"
	"github.com/grokify/aha-studio/ent/predicate"
)

// CommentUpdate is the builder for updating Comment entities.
type CommentUpdate struct {
	config
	hooks    []Hook
	mutation *CommentMutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdate) Where(ps ...predicate.Comment) *CommentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProduct sets the "product" field.
func (_u *CommentUpdate) SetProduct(v string) *CommentUpdate {
	_u.mutation.SetProduct(v)
	return _u
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableProduct(v *string) *CommentUpdate {
	if v != nil {
		_u.SetProduct(*v)
	}
	return _u
}

// ClearProduct clears the value of the "product" field.
func (_u *CommentUpdate) ClearProduct() *CommentUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// SetCommentableType sets the "commentable_type" field.
func (_u *CommentUpdate) SetCommentableType(v string) *CommentUpdate {
	_u.mutation.SetCommentableType(v)
	return _u
}

// SetNillableCommentableType sets the "commentable_type" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCommentableType(v *string) *CommentUpdate {
	if v != nil {
		_u.SetCommentableType(*v)
	}
	return _u
}

// ClearCommentableType clears the value of the "commentable_type" field.
func (_u *CommentUpdate) ClearCommentableType() *CommentUpdate {
	_u.mutation.ClearCommentableType()
	return _u
}

// SetCommentableID sets the "commentable_id" field.
func (_u *CommentUpdate) SetCommentableID(v string) *CommentUpdate {
	_u.mutation.SetCommentableID(v)
	return _u
}

// SetNillableCommentableID sets the "commentable_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCommentableID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetCommentableID(*v)
	}
	return _u
}

// ClearCommentableID clears the value of the "commentable_id" field.
func (_u *CommentUpdate) ClearCommentableID() *CommentUpdate {
	_u.mutation.ClearCommentableID()
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentUpdate) SetBody(v string) *CommentUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableBody(v *string) *CommentUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *CommentUpdate) ClearBody() *CommentUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdate) SetUserID(v string) *CommentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableUserID(v *string) *CommentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CommentUpdate) ClearUserID() *CommentUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetURL sets the "url" field.
func (_u *CommentUpdate) SetURL(v string) *CommentUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableURL(v *string) *CommentUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *CommentUpdate) ClearURL() *CommentUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentUpdate) SetCreatedAt(v time.Time) *CommentUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableCreatedAt(v *time.Time) *CommentUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CommentUpdate) ClearCreatedAt() *CommentUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdate) SetUpdatedAt(v time.Time) *CommentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CommentUpdate) SetNillableUpdatedAt(v *time.Time) *CommentUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CommentUpdate) ClearUpdatedAt() *CommentUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetData sets the "data" field.
func (_u *CommentUpdate) SetData(v map[string]interface{}) *CommentUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *CommentUpdate) ClearData() *CommentUpdate {
	_u.mutation.ClearData()
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdate) Mutation() *CommentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CommentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CommentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Product(); ok {
		_spec.SetField(comment.FieldProduct, field.TypeString, value)
	}
	if _u.mutation.ProductCleared() {
		_spec.ClearField(comment.FieldProduct, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableType(); ok {
		_spec.SetField(comment.FieldCommentableType, field.TypeString, value)
	}
	if _u.mutation.CommentableTypeCleared() {
		_spec.ClearField(comment.FieldCommentableType, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableID(); ok {
		_spec.SetField(comment.FieldCommentableID, field.TypeString, value)
	}
	if _u.mutation.CommentableIDCleared() {
		_spec.ClearField(comment.FieldCommentableID, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(comment.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(comment.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(comment.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(comment.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(comment.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(comment.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(comment.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(comment.FieldData, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CommentUpdateOne is the builder for updating a single Comment entity.
type CommentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommentMutation
}

// SetProduct sets the "product" field.
func (_u *CommentUpdateOne) SetProduct(v string) *CommentUpdateOne {
	_u.mutation.SetProduct(v)
	return _u
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableProduct(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetProduct(*v)
	}
	return _u
}

// ClearProduct clears the value of the "product" field.
func (_u *CommentUpdateOne) ClearProduct() *CommentUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// SetCommentableType sets the "commentable_type" field.
func (_u *CommentUpdateOne) SetCommentableType(v string) *CommentUpdateOne {
	_u.mutation.SetCommentableType(v)
	return _u
}

// SetNillableCommentableType sets the "commentable_type" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCommentableType(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetCommentableType(*v)
	}
	return _u
}

// ClearCommentableType clears the value of the "commentable_type" field.
func (_u *CommentUpdateOne) ClearCommentableType() *CommentUpdateOne {
	_u.mutation.ClearCommentableType()
	return _u
}

// SetCommentableID sets the "commentable_id" field.
func (_u *CommentUpdateOne) SetCommentableID(v string) *CommentUpdateOne {
	_u.mutation.SetCommentableID(v)
	return _u
}

// SetNillableCommentableID sets the "commentable_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCommentableID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetCommentableID(*v)
	}
	return _u
}

// ClearCommentableID clears the value of the "commentable_id" field.
func (_u *CommentUpdateOne) ClearCommentableID() *CommentUpdateOne {
	_u.mutation.ClearCommentableID()
	return _u
}

// SetBody sets the "body" field.
func (_u *CommentUpdateOne) SetBody(v string) *CommentUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableBody(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *CommentUpdateOne) ClearBody() *CommentUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CommentUpdateOne) SetUserID(v string) *CommentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableUserID(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CommentUpdateOne) ClearUserID() *CommentUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetURL sets the "url" field.
func (_u *CommentUpdateOne) SetURL(v string) *CommentUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableURL(v *string) *CommentUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *CommentUpdateOne) ClearURL() *CommentUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CommentUpdateOne) SetCreatedAt(v time.Time) *CommentUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableCreatedAt(v *time.Time) *CommentUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CommentUpdateOne) ClearCreatedAt() *CommentUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CommentUpdateOne) SetUpdatedAt(v time.Time) *CommentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CommentUpdateOne) SetNillableUpdatedAt(v *time.Time) *CommentUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CommentUpdateOne) ClearUpdatedAt() *CommentUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetData sets the "data" field.
func (_u *CommentUpdateOne) SetData(v map[string]interface{}) *CommentUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *CommentUpdateOne) ClearData() *CommentUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// Mutation returns the CommentMutation object of the builder.
func (_u *CommentUpdateOne) Mutation() *CommentMutation {
	return _u.mutation
}

// Where appends a list predicates to the CommentUpdate builder.
func (_u *CommentUpdateOne) Where(ps ...predicate.Comment) *CommentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CommentUpdateOne) Select(field string, fields ...string) *CommentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Comment entity.
func (_u *CommentUpdateOne) Save(ctx context.Context) (*Comment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CommentUpdateOne) SaveX(ctx context.Context) *Comment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CommentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CommentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CommentUpdateOne) sqlSave(ctx context.Context) (_node *Comment, err error) {
	_spec := sqlgraph.NewUpdateSpec(comment.Table, comment.Columns, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Comment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, comment.FieldID)
		for _, f := range fields {
			if !comment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != comment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Product(); ok {
		_spec.SetField(comment.FieldProduct, field.TypeString, value)
	}
	if _u.mutation.ProductCleared() {
		_spec.ClearField(comment.FieldProduct, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableType(); ok {
		_spec.SetField(comment.FieldCommentableType, field.TypeString, value)
	}
	if _u.mutation.CommentableTypeCleared() {
		_spec.ClearField(comment.FieldCommentableType, field.TypeString)
	}
	if value, ok := _u.mutation.CommentableID(); ok {
		_spec.SetField(comment.FieldCommentableID, field.TypeString, value)
	}
	if _u.mutation.CommentableIDCleared() {
		_spec.ClearField(comment.FieldCommentableID, field.TypeString)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(comment.FieldBody, field.TypeString, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(comment.FieldBody, field.TypeString)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(comment.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(comment.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(comment.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(comment.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(comment.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(comment.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(comment.FieldData, field.TypeJSON, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(comment.FieldData, field.TypeJSON)
	}
	_node = &Comment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{comment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
