// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/goal"
)

// GoalCreate is the builder for creating a Goal entity.
type GoalCreate struct {
	config
	mutation *GoalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProduct sets the "product" field.
func (_c *GoalCreate) SetProduct(v string) *GoalCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetReferenceNum sets the "reference_num" field.
func (_c *GoalCreate) SetReferenceNum(v string) *GoalCreate {
	_c.mutation.SetReferenceNum(v)
	return _c
}

// SetNillableReferenceNum sets the "reference_num" field if the given value is not nil.
func (_c *GoalCreate) SetNillableReferenceNum(v *string) *GoalCreate {
	if v != nil {
		_c.SetReferenceNum(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *GoalCreate) SetName(v string) *GoalCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *GoalCreate) SetNillableName(v *string) *GoalCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *GoalCreate) SetDescription(v string) *GoalCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *GoalCreate) SetNillableDescription(v *string) *GoalCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GoalCreate) SetStatus(v string) *GoalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GoalCreate) SetNillableStatus(v *string) *GoalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *GoalCreate) SetProgress(v float64) *GoalCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *GoalCreate) SetNillableProgress(v *float64) *GoalCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *GoalCreate) SetStartDate(v string) *GoalCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_c *GoalCreate) SetNillableStartDate(v *string) *GoalCreate {
	if v != nil {
		_c.SetStartDate(*v)
	}
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *GoalCreate) SetEndDate(v string) *GoalCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_c *GoalCreate) SetNillableEndDate(v *string) *GoalCreate {
	if v != nil {
		_c.SetEndDate(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *GoalCreate) SetURL(v string) *GoalCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *GoalCreate) SetNillableURL(v *string) *GoalCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoalCreate) SetCreatedAt(v time.Time) *GoalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoalCreate) SetNillableCreatedAt(v *time.Time) *GoalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GoalCreate) SetUpdatedAt(v time.Time) *GoalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GoalCreate) SetNillableUpdatedAt(v *time.Time) *GoalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetData sets the "data" field.
func (_c *GoalCreate) SetData(v map[string]interface{}) *GoalCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GoalCreate) SetID(v string) *GoalCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GoalMutation object of the builder.
func (_c *GoalCreate) Mutation() *GoalMutation {
	return _c.mutation
}

// Save creates the Goal in the database.
func (_c *GoalCreate) Save(ctx context.Context) (*Goal, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoalCreate) SaveX(ctx context.Context) *Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoalCreate) check() error {
	if _, ok := _c.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required field "Goal.product"`)}
	}
	return nil
}

func (_c *GoalCreate) sqlSave(ctx context.Context) (*Goal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Goal.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoalCreate) createSpec() (*Goal, *sqlgraph.CreateSpec) {
	var (
		_node = &Goal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goal.Table, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(goal.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.ReferenceNum(); ok {
		_spec.SetField(goal.FieldReferenceNum, field.TypeString, value)
		_node.ReferenceNum = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(goal.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(goal.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(goal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(goal.FieldProgress, field.TypeFloat64, value)
		_node.Progress = &value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(goal.FieldStartDate, field.TypeString, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(goal.FieldEndDate, field.TypeString, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(goal.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(goal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(goal.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Goal.Create().
//		SetProduct(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GoalUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *GoalCreate) OnConflict(opts ...sql.ConflictOption) *GoalUpsertOne {
	_c.conflict = opts
	return &GoalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Goal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GoalCreate) OnConflictColumns(columns ...string) *GoalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GoalUpsertOne{
		create: _c,
	}
}

type (
	// GoalUpsertOne is the builder for "upsert"-ing
	//  one Goal node.
	GoalUpsertOne struct {
		create *GoalCreate
	}

	// GoalUpsert is the "OnConflict" setter.
	GoalUpsert struct {
		*sql.UpdateSet
	}
)

// SetProduct sets the "product" field.
func (u *GoalUpsert) SetProduct(v string) *GoalUpsert {
	u.Set(goal.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *GoalUpsert) UpdateProduct() *GoalUpsert {
	u.SetExcluded(goal.FieldProduct)
	return u
}

// SetReferenceNum sets the "reference_num" field.
func (u *GoalUpsert) SetReferenceNum(v string) *GoalUpsert {
	u.Set(goal.FieldReferenceNum, v)
	return u
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *GoalUpsert) UpdateReferenceNum() *GoalUpsert {
	u.SetExcluded(goal.FieldReferenceNum)
	return u
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *GoalUpsert) ClearReferenceNum() *GoalUpsert {
	u.SetNull(goal.FieldReferenceNum)
	return u
}

// SetName sets the "name" field.
func (u *GoalUpsert) SetName(v string) *GoalUpsert {
	u.Set(goal.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GoalUpsert) UpdateName() *GoalUpsert {
	u.SetExcluded(goal.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *GoalUpsert) ClearName() *GoalUpsert {
	u.SetNull(goal.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *GoalUpsert) SetDescription(v string) *GoalUpsert {
	u.Set(goal.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GoalUpsert) UpdateDescription() *GoalUpsert {
	u.SetExcluded(goal.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *GoalUpsert) ClearDescription() *GoalUpsert {
	u.SetNull(goal.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *GoalUpsert) SetStatus(v string) *GoalUpsert {
	u.Set(goal.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoalUpsert) UpdateStatus() *GoalUpsert {
	u.SetExcluded(goal.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *GoalUpsert) ClearStatus() *GoalUpsert {
	u.SetNull(goal.FieldStatus)
	return u
}

// SetProgress sets the "progress" field.
func (u *GoalUpsert) SetProgress(v float64) *GoalUpsert {
	u.Set(goal.FieldProgress, v)
	return u
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *GoalUpsert) UpdateProgress() *GoalUpsert {
	u.SetExcluded(goal.FieldProgress)
	return u
}

// AddProgress adds v to the "progress" field.
func (u *GoalUpsert) AddProgress(v float64) *GoalUpsert {
	u.Add(goal.FieldProgress, v)
	return u
}

// ClearProgress clears the value of the "progress" field.
func (u *GoalUpsert) ClearProgress() *GoalUpsert {
	u.SetNull(goal.FieldProgress)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *GoalUpsert) SetStartDate(v string) *GoalUpsert {
	u.Set(goal.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *GoalUpsert) UpdateStartDate() *GoalUpsert {
	u.SetExcluded(goal.FieldStartDate)
	return u
}

// ClearStartDate clears the value of the "start_date" field.
func (u *GoalUpsert) ClearStartDate() *GoalUpsert {
	u.SetNull(goal.FieldStartDate)
	return u
}

// SetEndDate sets the "end_date" field.
func (u *GoalUpsert) SetEndDate(v string) *GoalUpsert {
	u.Set(goal.FieldEndDate, v)
	return u
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *GoalUpsert) UpdateEndDate() *GoalUpsert {
	u.SetExcluded(goal.FieldEndDate)
	return u
}

// ClearEndDate clears the value of the "end_date" field.
func (u *GoalUpsert) ClearEndDate() *GoalUpsert {
	u.SetNull(goal.FieldEndDate)
	return u
}

// SetURL sets the "url" field.
func (u *GoalUpsert) SetURL(v string) *GoalUpsert {
	u.Set(goal.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GoalUpsert) UpdateURL() *GoalUpsert {
	u.SetExcluded(goal.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *GoalUpsert) ClearURL() *GoalUpsert {
	u.SetNull(goal.FieldURL)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GoalUpsert) SetCreatedAt(v time.Time) *GoalUpsert {
	u.Set(goal.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GoalUpsert) UpdateCreatedAt() *GoalUpsert {
	u.SetExcluded(goal.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *GoalUpsert) ClearCreatedAt() *GoalUpsert {
	u.SetNull(goal.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GoalUpsert) SetUpdatedAt(v time.Time) *GoalUpsert {
	u.Set(goal.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GoalUpsert) UpdateUpdatedAt() *GoalUpsert {
	u.SetExcluded(goal.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GoalUpsert) ClearUpdatedAt() *GoalUpsert {
	u.SetNull(goal.FieldUpdatedAt)
	return u
}

// SetData sets the "data" field.
func (u *GoalUpsert) SetData(v map[string]interface{}) *GoalUpsert {
	u.Set(goal.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *GoalUpsert) UpdateData() *GoalUpsert {
	u.SetExcluded(goal.FieldData)
	return u
}

// ClearData clears the value of the "data" field.
func (u *GoalUpsert) ClearData() *GoalUpsert {
	u.SetNull(goal.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Goal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(goal.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GoalUpsertOne) UpdateNewValues() *GoalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(goal.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Goal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GoalUpsertOne) Ignore() *GoalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GoalUpsertOne) DoNothing() *GoalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GoalCreate.OnConflict
// documentation for more info.
func (u *GoalUpsertOne) Update(set func(*GoalUpsert)) *GoalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GoalUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *GoalUpsertOne) SetProduct(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateProduct() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateProduct()
	})
}

// SetReferenceNum sets the "reference_num" field.
func (u *GoalUpsertOne) SetReferenceNum(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetReferenceNum(v)
	})
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateReferenceNum() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateReferenceNum()
	})
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *GoalUpsertOne) ClearReferenceNum() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearReferenceNum()
	})
}

// SetName sets the "name" field.
func (u *GoalUpsertOne) SetName(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateName() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *GoalUpsertOne) ClearName() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *GoalUpsertOne) SetDescription(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateDescription() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *GoalUpsertOne) ClearDescription() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *GoalUpsertOne) SetStatus(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateStatus() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *GoalUpsertOne) ClearStatus() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *GoalUpsertOne) SetProgress(v float64) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *GoalUpsertOne) AddProgress(v float64) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateProgress() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateProgress()
	})
}

// ClearProgress clears the value of the "progress" field.
func (u *GoalUpsertOne) ClearProgress() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearProgress()
	})
}

// SetStartDate sets the "start_date" field.
func (u *GoalUpsertOne) SetStartDate(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateStartDate() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateStartDate()
	})
}

// ClearStartDate clears the value of the "start_date" field.
func (u *GoalUpsertOne) ClearStartDate() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *GoalUpsertOne) SetEndDate(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateEndDate() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateEndDate()
	})
}

// ClearEndDate clears the value of the "end_date" field.
func (u *GoalUpsertOne) ClearEndDate() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearEndDate()
	})
}

// SetURL sets the "url" field.
func (u *GoalUpsertOne) SetURL(v string) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateURL() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *GoalUpsertOne) ClearURL() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearURL()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GoalUpsertOne) SetCreatedAt(v time.Time) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateCreatedAt() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *GoalUpsertOne) ClearCreatedAt() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GoalUpsertOne) SetUpdatedAt(v time.Time) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateUpdatedAt() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GoalUpsertOne) ClearUpdatedAt() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetData sets the "data" field.
func (u *GoalUpsertOne) SetData(v map[string]interface{}) *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *GoalUpsertOne) UpdateData() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *GoalUpsertOne) ClearData() *GoalUpsertOne {
	return u.Update(func(s *GoalUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *GoalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GoalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GoalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GoalUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GoalUpsertOne.ID is not supported by MySQL driver. Use GoalUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GoalUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GoalCreateBulk is the builder for creating many Goal entities in bulk.
type GoalCreateBulk struct {
	config
	err      error
	builders []*GoalCreate
	conflict []sql.ConflictOption
}

// Save creates the Goal entities in the database.
func (_c *GoalCreateBulk) Save(ctx context.Context) ([]*Goal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Goal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoalCreateBulk) SaveX(ctx context.Context) []*Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Goal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GoalUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *GoalCreateBulk) OnConflict(opts ...sql.ConflictOption) *GoalUpsertBulk {
	_c.conflict = opts
	return &GoalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Goal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GoalCreateBulk) OnConflictColumns(columns ...string) *GoalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GoalUpsertBulk{
		create: _c,
	}
}

// GoalUpsertBulk is the builder for "upsert"-ing
// a bulk of Goal nodes.
type GoalUpsertBulk struct {
	create *GoalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Goal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(goal.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GoalUpsertBulk) UpdateNewValues() *GoalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(goal.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Goal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GoalUpsertBulk) Ignore() *GoalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GoalUpsertBulk) DoNothing() *GoalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GoalCreateBulk.OnConflict
// documentation for more info.
func (u *GoalUpsertBulk) Update(set func(*GoalUpsert)) *GoalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GoalUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *GoalUpsertBulk) SetProduct(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateProduct() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateProduct()
	})
}

// SetReferenceNum sets the "reference_num" field.
func (u *GoalUpsertBulk) SetReferenceNum(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetReferenceNum(v)
	})
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateReferenceNum() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateReferenceNum()
	})
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *GoalUpsertBulk) ClearReferenceNum() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearReferenceNum()
	})
}

// SetName sets the "name" field.
func (u *GoalUpsertBulk) SetName(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateName() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *GoalUpsertBulk) ClearName() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *GoalUpsertBulk) SetDescription(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateDescription() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *GoalUpsertBulk) ClearDescription() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *GoalUpsertBulk) SetStatus(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateStatus() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *GoalUpsertBulk) ClearStatus() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *GoalUpsertBulk) SetProgress(v float64) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetProgress(v)
	})
}

// AddProgress adds v to the "progress" field.
func (u *GoalUpsertBulk) AddProgress(v float64) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.AddProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateProgress() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateProgress()
	})
}

// ClearProgress clears the value of the "progress" field.
func (u *GoalUpsertBulk) ClearProgress() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearProgress()
	})
}

// SetStartDate sets the "start_date" field.
func (u *GoalUpsertBulk) SetStartDate(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateStartDate() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateStartDate()
	})
}

// ClearStartDate clears the value of the "start_date" field.
func (u *GoalUpsertBulk) ClearStartDate() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *GoalUpsertBulk) SetEndDate(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateEndDate() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateEndDate()
	})
}

// ClearEndDate clears the value of the "end_date" field.
func (u *GoalUpsertBulk) ClearEndDate() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearEndDate()
	})
}

// SetURL sets the "url" field.
func (u *GoalUpsertBulk) SetURL(v string) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateURL() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *GoalUpsertBulk) ClearURL() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearURL()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *GoalUpsertBulk) SetCreatedAt(v time.Time) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateCreatedAt() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *GoalUpsertBulk) ClearCreatedAt() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GoalUpsertBulk) SetUpdatedAt(v time.Time) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateUpdatedAt() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GoalUpsertBulk) ClearUpdatedAt() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetData sets the "data" field.
func (u *GoalUpsertBulk) SetData(v map[string]interface{}) *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *GoalUpsertBulk) UpdateData() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *GoalUpsertBulk) ClearData() *GoalUpsertBulk {
	return u.Update(func(s *GoalUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *GoalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GoalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GoalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GoalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
