// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/ideauser"
)

// IdeaUserCreate is the builder for creating a IdeaUser entity.
type IdeaUserCreate struct {
	config
	mutation *IdeaUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *IdeaUserCreate) SetName(v string) *IdeaUserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *IdeaUserCreate) SetNillableName(v *string) *IdeaUserCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *IdeaUserCreate) SetEmail(v string) *IdeaUserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *IdeaUserCreate) SetNillableEmail(v *string) *IdeaUserCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdeaUserCreate) SetCreatedAt(v time.Time) *IdeaUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdeaUserCreate) SetNillableCreatedAt(v *time.Time) *IdeaUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetIdeaOrganizations sets the "idea_organizations" field.
func (_c *IdeaUserCreate) SetIdeaOrganizations(v []map[string]interface{}) *IdeaUserCreate {
	_c.mutation.SetIdeaOrganizations(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IdeaUserCreate) SetID(v string) *IdeaUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IdeaUserMutation object of the builder.
func (_c *IdeaUserCreate) Mutation() *IdeaUserMutation {
	return _c.mutation
}

// Save creates the IdeaUser in the database.
func (_c *IdeaUserCreate) Save(ctx context.Context) (*IdeaUser, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdeaUserCreate) SaveX(ctx context.Context) *IdeaUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdeaUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdeaUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdeaUserCreate) check() error {
	return nil
}

func (_c *IdeaUserCreate) sqlSave(ctx context.Context) (*IdeaUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IdeaUser.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdeaUserCreate) createSpec() (*IdeaUser, *sqlgraph.CreateSpec) {
	var (
		_node = &IdeaUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ideauser.Table, sqlgraph.NewFieldSpec(ideauser.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ideauser.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(ideauser.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ideauser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.IdeaOrganizations(); ok {
		_spec.SetField(ideauser.FieldIdeaOrganizations, field.TypeJSON, value)
		_node.IdeaOrganizations = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdeaUser.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdeaUserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *IdeaUserCreate) OnConflict(opts ...sql.ConflictOption) *IdeaUserUpsertOne {
	_c.conflict = opts
	return &IdeaUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdeaUserCreate) OnConflictColumns(columns ...string) *IdeaUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdeaUserUpsertOne{
		create: _c,
	}
}

type (
	// IdeaUserUpsertOne is the builder for "upsert"-ing
	//  one IdeaUser node.
	IdeaUserUpsertOne struct {
		create *IdeaUserCreate
	}

	// IdeaUserUpsert is the "OnConflict" setter.
	IdeaUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *IdeaUserUpsert) SetName(v string) *IdeaUserUpsert {
	u.Set(ideauser.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IdeaUserUpsert) UpdateName() *IdeaUserUpsert {
	u.SetExcluded(ideauser.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *IdeaUserUpsert) ClearName() *IdeaUserUpsert {
	u.SetNull(ideauser.FieldName)
	return u
}

// SetEmail sets the "email" field.
func (u *IdeaUserUpsert) SetEmail(v string) *IdeaUserUpsert {
	u.Set(ideauser.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *IdeaUserUpsert) UpdateEmail() *IdeaUserUpsert {
	u.SetExcluded(ideauser.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *IdeaUserUpsert) ClearEmail() *IdeaUserUpsert {
	u.SetNull(ideauser.FieldEmail)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaUserUpsert) SetCreatedAt(v time.Time) *IdeaUserUpsert {
	u.Set(ideauser.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaUserUpsert) UpdateCreatedAt() *IdeaUserUpsert {
	u.SetExcluded(ideauser.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaUserUpsert) ClearCreatedAt() *IdeaUserUpsert {
	u.SetNull(ideauser.FieldCreatedAt)
	return u
}

// SetIdeaOrganizations sets the "idea_organizations" field.
func (u *IdeaUserUpsert) SetIdeaOrganizations(v []map[string]interface{}) *IdeaUserUpsert {
	u.Set(ideauser.FieldIdeaOrganizations, v)
	return u
}

// UpdateIdeaOrganizations sets the "idea_organizations" field to the value that was provided on create.
func (u *IdeaUserUpsert) UpdateIdeaOrganizations() *IdeaUserUpsert {
	u.SetExcluded(ideauser.FieldIdeaOrganizations)
	return u
}

// ClearIdeaOrganizations clears the value of the "idea_organizations" field.
func (u *IdeaUserUpsert) ClearIdeaOrganizations() *IdeaUserUpsert {
	u.SetNull(ideauser.FieldIdeaOrganizations)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ideauser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdeaUserUpsertOne) UpdateNewValues() *IdeaUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ideauser.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IdeaUserUpsertOne) Ignore() *IdeaUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdeaUserUpsertOne) DoNothing() *IdeaUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdeaUserCreate.OnConflict
// documentation for more info.
func (u *IdeaUserUpsertOne) Update(set func(*IdeaUserUpsert)) *IdeaUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdeaUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *IdeaUserUpsertOne) SetName(v string) *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IdeaUserUpsertOne) UpdateName() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *IdeaUserUpsertOne) ClearName() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearName()
	})
}

// SetEmail sets the "email" field.
func (u *IdeaUserUpsertOne) SetEmail(v string) *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *IdeaUserUpsertOne) UpdateEmail() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *IdeaUserUpsertOne) ClearEmail() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearEmail()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaUserUpsertOne) SetCreatedAt(v time.Time) *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaUserUpsertOne) UpdateCreatedAt() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaUserUpsertOne) ClearCreatedAt() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearCreatedAt()
	})
}

// SetIdeaOrganizations sets the "idea_organizations" field.
func (u *IdeaUserUpsertOne) SetIdeaOrganizations(v []map[string]interface{}) *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetIdeaOrganizations(v)
	})
}

// UpdateIdeaOrganizations sets the "idea_organizations" field to the value that was provided on create.
func (u *IdeaUserUpsertOne) UpdateIdeaOrganizations() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateIdeaOrganizations()
	})
}

// ClearIdeaOrganizations clears the value of the "idea_organizations" field.
func (u *IdeaUserUpsertOne) ClearIdeaOrganizations() *IdeaUserUpsertOne {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearIdeaOrganizations()
	})
}

// Exec executes the query.
func (u *IdeaUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdeaUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdeaUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IdeaUserUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IdeaUserUpsertOne.ID is not supported by MySQL driver. Use IdeaUserUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IdeaUserUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IdeaUserCreateBulk is the builder for creating many IdeaUser entities in bulk.
type IdeaUserCreateBulk struct {
	config
	err      error
	builders []*IdeaUserCreate
	conflict []sql.ConflictOption
}

// Save creates the IdeaUser entities in the database.
func (_c *IdeaUserCreateBulk) Save(ctx context.Context) ([]*IdeaUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdeaUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdeaUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdeaUserCreateBulk) SaveX(ctx context.Context) []*IdeaUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdeaUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdeaUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdeaUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdeaUserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *IdeaUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *IdeaUserUpsertBulk {
	_c.conflict = opts
	return &IdeaUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdeaUserCreateBulk) OnConflictColumns(columns ...string) *IdeaUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdeaUserUpsertBulk{
		create: _c,
	}
}

// IdeaUserUpsertBulk is the builder for "upsert"-ing
// a bulk of IdeaUser nodes.
type IdeaUserUpsertBulk struct {
	create *IdeaUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ideauser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdeaUserUpsertBulk) UpdateNewValues() *IdeaUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ideauser.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdeaUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IdeaUserUpsertBulk) Ignore() *IdeaUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdeaUserUpsertBulk) DoNothing() *IdeaUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdeaUserCreateBulk.OnConflict
// documentation for more info.
func (u *IdeaUserUpsertBulk) Update(set func(*IdeaUserUpsert)) *IdeaUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdeaUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *IdeaUserUpsertBulk) SetName(v string) *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IdeaUserUpsertBulk) UpdateName() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *IdeaUserUpsertBulk) ClearName() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearName()
	})
}

// SetEmail sets the "email" field.
func (u *IdeaUserUpsertBulk) SetEmail(v string) *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *IdeaUserUpsertBulk) UpdateEmail() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *IdeaUserUpsertBulk) ClearEmail() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearEmail()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaUserUpsertBulk) SetCreatedAt(v time.Time) *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaUserUpsertBulk) UpdateCreatedAt() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaUserUpsertBulk) ClearCreatedAt() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearCreatedAt()
	})
}

// SetIdeaOrganizations sets the "idea_organizations" field.
func (u *IdeaUserUpsertBulk) SetIdeaOrganizations(v []map[string]interface{}) *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.SetIdeaOrganizations(v)
	})
}

// UpdateIdeaOrganizations sets the "idea_organizations" field to the value that was provided on create.
func (u *IdeaUserUpsertBulk) UpdateIdeaOrganizations() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.UpdateIdeaOrganizations()
	})
}

// ClearIdeaOrganizations clears the value of the "idea_organizations" field.
func (u *IdeaUserUpsertBulk) ClearIdeaOrganizations() *IdeaUserUpsertBulk {
	return u.Update(func(s *IdeaUserUpsert) {
		s.ClearIdeaOrganizations()
	})
}

// Exec executes the query.
func (u *IdeaUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IdeaUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdeaUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdeaUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
