// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/ideaorganization"
)

// IdeaOrganization is the model entity for the IdeaOrganization schema.
type IdeaOrganization struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ReferenceNum holds the value of the "reference_num" field.
	ReferenceNum string `json:"reference_num,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// EmailDomains holds the value of the "email_domains" field.
	EmailDomains string `json:"email_domains,omitempty"`
	// Revenue holds the value of the "revenue" field.
	Revenue *float64 `json:"revenue,omitempty"`
	// EndorsementsCount holds the value of the "endorsements_count" field.
	EndorsementsCount int `json:"endorsements_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdeaOrganization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ideaorganization.FieldRevenue:
			values[i] = new(sql.NullFloat64)
		case ideaorganization.FieldEndorsementsCount:
			values[i] = new(sql.NullInt64)
		case ideaorganization.FieldID, ideaorganization.FieldName, ideaorganization.FieldReferenceNum, ideaorganization.FieldURL, ideaorganization.FieldEmailDomains:
			values[i] = new(sql.NullString)
		case ideaorganization.FieldCreatedAt, ideaorganization.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdeaOrganization fields.
func (_m *IdeaOrganization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ideaorganization.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ideaorganization.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ideaorganization.FieldReferenceNum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_num", values[i])
			} else if value.Valid {
				_m.ReferenceNum = value.String
			}
		case ideaorganization.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case ideaorganization.FieldEmailDomains:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email_domains", values[i])
			} else if value.Valid {
				_m.EmailDomains = value.String
			}
		case ideaorganization.FieldRevenue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field revenue", values[i])
			} else if value.Valid {
				_m.Revenue = new(float64)
				*_m.Revenue = value.Float64
			}
		case ideaorganization.FieldEndorsementsCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field endorsements_count", values[i])
			} else if value.Valid {
				_m.EndorsementsCount = int(value.Int64)
			}
		case ideaorganization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case ideaorganization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IdeaOrganization.
// This includes values selected through modifiers, order, etc.
func (_m *IdeaOrganization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IdeaOrganization.
// Note that you need to call IdeaOrganization.Unwrap() before calling this method if this IdeaOrganization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdeaOrganization) Update() *IdeaOrganizationUpdateOne {
	return NewIdeaOrganizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdeaOrganization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdeaOrganization) Unwrap() *IdeaOrganization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdeaOrganization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdeaOrganization) String() string {
	var builder strings.Builder
	builder.WriteString("IdeaOrganization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("reference_num=")
	builder.WriteString(_m.ReferenceNum)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("email_domains=")
	builder.WriteString(_m.EmailDomains)
	builder.WriteString(", ")
	if v := _m.Revenue; v != nil {
		builder.WriteString("revenue=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("endorsements_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndorsementsCount))
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// IdeaOrganizations is a parsable slice of IdeaOrganization.
type IdeaOrganizations []*IdeaOrganization
