// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/ideaorganization"
	"github.com/grokify/aha-studio/ent/predicate"
)

// IdeaOrganizationUpdate is the builder for updating IdeaOrganization entities.
type IdeaOrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *IdeaOrganizationMutation
}

// Where appends a list predicates to the IdeaOrganizationUpdate builder.
func (_u *IdeaOrganizationUpdate) Where(ps ...predicate.IdeaOrganization) *IdeaOrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *IdeaOrganizationUpdate) SetName(v string) *IdeaOrganizationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableName(v *string) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *IdeaOrganizationUpdate) ClearName() *IdeaOrganizationUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetReferenceNum sets the "reference_num" field.
func (_u *IdeaOrganizationUpdate) SetReferenceNum(v string) *IdeaOrganizationUpdate {
	_u.mutation.SetReferenceNum(v)
	return _u
}

// SetNillableReferenceNum sets the "reference_num" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableReferenceNum(v *string) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetReferenceNum(*v)
	}
	return _u
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (_u *IdeaOrganizationUpdate) ClearReferenceNum() *IdeaOrganizationUpdate {
	_u.mutation.ClearReferenceNum()
	return _u
}

// SetURL sets the "url" field.
func (_u *IdeaOrganizationUpdate) SetURL(v string) *IdeaOrganizationUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableURL(v *string) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *IdeaOrganizationUpdate) ClearURL() *IdeaOrganizationUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetEmailDomains sets the "email_domains" field.
func (_u *IdeaOrganizationUpdate) SetEmailDomains(v string) *IdeaOrganizationUpdate {
	_u.mutation.SetEmailDomains(v)
	return _u
}

// SetNillableEmailDomains sets the "email_domains" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableEmailDomains(v *string) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetEmailDomains(*v)
	}
	return _u
}

// ClearEmailDomains clears the value of the "email_domains" field.
func (_u *IdeaOrganizationUpdate) ClearEmailDomains() *IdeaOrganizationUpdate {
	_u.mutation.ClearEmailDomains()
	return _u
}

// SetRevenue sets the "revenue" field.
func (_u *IdeaOrganizationUpdate) SetRevenue(v float64) *IdeaOrganizationUpdate {
	_u.mutation.ResetRevenue()
	_u.mutation.SetRevenue(v)
	return _u
}

// SetNillableRevenue sets the "revenue" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableRevenue(v *float64) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetRevenue(*v)
	}
	return _u
}

// AddRevenue adds value to the "revenue" field.
func (_u *IdeaOrganizationUpdate) AddRevenue(v float64) *IdeaOrganizationUpdate {
	_u.mutation.AddRevenue(v)
	return _u
}

// ClearRevenue clears the value of the "revenue" field.
func (_u *IdeaOrganizationUpdate) ClearRevenue() *IdeaOrganizationUpdate {
	_u.mutation.ClearRevenue()
	return _u
}

// SetEndorsementsCount sets the "endorsements_count" field.
func (_u *IdeaOrganizationUpdate) SetEndorsementsCount(v int) *IdeaOrganizationUpdate {
	_u.mutation.ResetEndorsementsCount()
	_u.mutation.SetEndorsementsCount(v)
	return _u
}

// SetNillableEndorsementsCount sets the "endorsements_count" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableEndorsementsCount(v *int) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetEndorsementsCount(*v)
	}
	return _u
}

// AddEndorsementsCount adds value to the "endorsements_count" field.
func (_u *IdeaOrganizationUpdate) AddEndorsementsCount(v int) *IdeaOrganizationUpdate {
	_u.mutation.AddEndorsementsCount(v)
	return _u
}

// ClearEndorsementsCount clears the value of the "endorsements_count" field.
func (_u *IdeaOrganizationUpdate) ClearEndorsementsCount() *IdeaOrganizationUpdate {
	_u.mutation.ClearEndorsementsCount()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IdeaOrganizationUpdate) SetCreatedAt(v time.Time) *IdeaOrganizationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableCreatedAt(v *time.Time) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IdeaOrganizationUpdate) ClearCreatedAt() *IdeaOrganizationUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdeaOrganizationUpdate) SetUpdatedAt(v time.Time) *IdeaOrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IdeaOrganizationUpdate) SetNillableUpdatedAt(v *time.Time) *IdeaOrganizationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *IdeaOrganizationUpdate) ClearUpdatedAt() *IdeaOrganizationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the IdeaOrganizationMutation object of the builder.
func (_u *IdeaOrganizationUpdate) Mutation() *IdeaOrganizationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdeaOrganizationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdeaOrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdeaOrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdeaOrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IdeaOrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ideaorganization.Table, ideaorganization.Columns, sqlgraph.NewFieldSpec(ideaorganization.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ideaorganization.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(ideaorganization.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceNum(); ok {
		_spec.SetField(ideaorganization.FieldReferenceNum, field.TypeString, value)
	}
	if _u.mutation.ReferenceNumCleared() {
		_spec.ClearField(ideaorganization.FieldReferenceNum, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ideaorganization.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(ideaorganization.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.EmailDomains(); ok {
		_spec.SetField(ideaorganization.FieldEmailDomains, field.TypeString, value)
	}
	if _u.mutation.EmailDomainsCleared() {
		_spec.ClearField(ideaorganization.FieldEmailDomains, field.TypeString)
	}
	if value, ok := _u.mutation.Revenue(); ok {
		_spec.SetField(ideaorganization.FieldRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenue(); ok {
		_spec.AddField(ideaorganization.FieldRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.RevenueCleared() {
		_spec.ClearField(ideaorganization.FieldRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.EndorsementsCount(); ok {
		_spec.SetField(ideaorganization.FieldEndorsementsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndorsementsCount(); ok {
		_spec.AddField(ideaorganization.FieldEndorsementsCount, field.TypeInt, value)
	}
	if _u.mutation.EndorsementsCountCleared() {
		_spec.ClearField(ideaorganization.FieldEndorsementsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ideaorganization.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(ideaorganization.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ideaorganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(ideaorganization.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ideaorganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdeaOrganizationUpdateOne is the builder for updating a single IdeaOrganization entity.
type IdeaOrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdeaOrganizationMutation
}

// SetName sets the "name" field.
func (_u *IdeaOrganizationUpdateOne) SetName(v string) *IdeaOrganizationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableName(v *string) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *IdeaOrganizationUpdateOne) ClearName() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetReferenceNum sets the "reference_num" field.
func (_u *IdeaOrganizationUpdateOne) SetReferenceNum(v string) *IdeaOrganizationUpdateOne {
	_u.mutation.SetReferenceNum(v)
	return _u
}

// SetNillableReferenceNum sets the "reference_num" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableReferenceNum(v *string) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetReferenceNum(*v)
	}
	return _u
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (_u *IdeaOrganizationUpdateOne) ClearReferenceNum() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearReferenceNum()
	return _u
}

// SetURL sets the "url" field.
func (_u *IdeaOrganizationUpdateOne) SetURL(v string) *IdeaOrganizationUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableURL(v *string) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *IdeaOrganizationUpdateOne) ClearURL() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetEmailDomains sets the "email_domains" field.
func (_u *IdeaOrganizationUpdateOne) SetEmailDomains(v string) *IdeaOrganizationUpdateOne {
	_u.mutation.SetEmailDomains(v)
	return _u
}

// SetNillableEmailDomains sets the "email_domains" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableEmailDomains(v *string) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetEmailDomains(*v)
	}
	return _u
}

// ClearEmailDomains clears the value of the "email_domains" field.
func (_u *IdeaOrganizationUpdateOne) ClearEmailDomains() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearEmailDomains()
	return _u
}

// SetRevenue sets the "revenue" field.
func (_u *IdeaOrganizationUpdateOne) SetRevenue(v float64) *IdeaOrganizationUpdateOne {
	_u.mutation.ResetRevenue()
	_u.mutation.SetRevenue(v)
	return _u
}

// SetNillableRevenue sets the "revenue" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableRevenue(v *float64) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetRevenue(*v)
	}
	return _u
}

// AddRevenue adds value to the "revenue" field.
func (_u *IdeaOrganizationUpdateOne) AddRevenue(v float64) *IdeaOrganizationUpdateOne {
	_u.mutation.AddRevenue(v)
	return _u
}

// ClearRevenue clears the value of the "revenue" field.
func (_u *IdeaOrganizationUpdateOne) ClearRevenue() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearRevenue()
	return _u
}

// SetEndorsementsCount sets the "endorsements_count" field.
func (_u *IdeaOrganizationUpdateOne) SetEndorsementsCount(v int) *IdeaOrganizationUpdateOne {
	_u.mutation.ResetEndorsementsCount()
	_u.mutation.SetEndorsementsCount(v)
	return _u
}

// SetNillableEndorsementsCount sets the "endorsements_count" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableEndorsementsCount(v *int) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetEndorsementsCount(*v)
	}
	return _u
}

// AddEndorsementsCount adds value to the "endorsements_count" field.
func (_u *IdeaOrganizationUpdateOne) AddEndorsementsCount(v int) *IdeaOrganizationUpdateOne {
	_u.mutation.AddEndorsementsCount(v)
	return _u
}

// ClearEndorsementsCount clears the value of the "endorsements_count" field.
func (_u *IdeaOrganizationUpdateOne) ClearEndorsementsCount() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearEndorsementsCount()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IdeaOrganizationUpdateOne) SetCreatedAt(v time.Time) *IdeaOrganizationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableCreatedAt(v *time.Time) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *IdeaOrganizationUpdateOne) ClearCreatedAt() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdeaOrganizationUpdateOne) SetUpdatedAt(v time.Time) *IdeaOrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *IdeaOrganizationUpdateOne) SetNillableUpdatedAt(v *time.Time) *IdeaOrganizationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *IdeaOrganizationUpdateOne) ClearUpdatedAt() *IdeaOrganizationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the IdeaOrganizationMutation object of the builder.
func (_u *IdeaOrganizationUpdateOne) Mutation() *IdeaOrganizationMutation {
	return _u.mutation
}

// Where appends a list predicates to the IdeaOrganizationUpdate builder.
func (_u *IdeaOrganizationUpdateOne) Where(ps ...predicate.IdeaOrganization) *IdeaOrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdeaOrganizationUpdateOne) Select(field string, fields ...string) *IdeaOrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IdeaOrganization entity.
func (_u *IdeaOrganizationUpdateOne) Save(ctx context.Context) (*IdeaOrganization, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdeaOrganizationUpdateOne) SaveX(ctx context.Context) *IdeaOrganization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdeaOrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdeaOrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *IdeaOrganizationUpdateOne) sqlSave(ctx context.Context) (_node *IdeaOrganization, err error) {
	_spec := sqlgraph.NewUpdateSpec(ideaorganization.Table, ideaorganization.Columns, sqlgraph.NewFieldSpec(ideaorganization.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdeaOrganization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ideaorganization.FieldID)
		for _, f := range fields {
			if !ideaorganization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ideaorganization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ideaorganization.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(ideaorganization.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.ReferenceNum(); ok {
		_spec.SetField(ideaorganization.FieldReferenceNum, field.TypeString, value)
	}
	if _u.mutation.ReferenceNumCleared() {
		_spec.ClearField(ideaorganization.FieldReferenceNum, field.TypeString)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(ideaorganization.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(ideaorganization.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.EmailDomains(); ok {
		_spec.SetField(ideaorganization.FieldEmailDomains, field.TypeString, value)
	}
	if _u.mutation.EmailDomainsCleared() {
		_spec.ClearField(ideaorganization.FieldEmailDomains, field.TypeString)
	}
	if value, ok := _u.mutation.Revenue(); ok {
		_spec.SetField(ideaorganization.FieldRevenue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRevenue(); ok {
		_spec.AddField(ideaorganization.FieldRevenue, field.TypeFloat64, value)
	}
	if _u.mutation.RevenueCleared() {
		_spec.ClearField(ideaorganization.FieldRevenue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.EndorsementsCount(); ok {
		_spec.SetField(ideaorganization.FieldEndorsementsCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndorsementsCount(); ok {
		_spec.AddField(ideaorganization.FieldEndorsementsCount, field.TypeInt, value)
	}
	if _u.mutation.EndorsementsCountCleared() {
		_spec.ClearField(ideaorganization.FieldEndorsementsCount, field.TypeInt)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(ideaorganization.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(ideaorganization.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ideaorganization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(ideaorganization.FieldUpdatedAt, field.TypeTime)
	}
	_node = &IdeaOrganization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ideaorganization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
