// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/ideaendorsement"
)

// IdeaEndorsement is the model entity for the IdeaEndorsement schema.
type IdeaEndorsement struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Product holds the value of the "product" field.
	Product string `json:"product,omitempty"`
	// IdeaID holds the value of the "idea_id" field.
	IdeaID string `json:"idea_id,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// PortalUserID holds the value of the "portal_user_id" field.
	PortalUserID string `json:"portal_user_id,omitempty"`
	// PortalUserName holds the value of the "portal_user_name" field.
	PortalUserName string `json:"portal_user_name,omitempty"`
	// PortalUserEmail holds the value of the "portal_user_email" field.
	PortalUserEmail string `json:"portal_user_email,omitempty"`
	// PortalUserCreatedAt holds the value of the "portal_user_created_at" field.
	PortalUserCreatedAt *time.Time `json:"portal_user_created_at,omitempty"`
	// IdeaUserID holds the value of the "idea_user_id" field.
	IdeaUserID string `json:"idea_user_id,omitempty"`
	// IdeaUserName holds the value of the "idea_user_name" field.
	IdeaUserName string `json:"idea_user_name,omitempty"`
	// IdeaUserEmail holds the value of the "idea_user_email" field.
	IdeaUserEmail string `json:"idea_user_email,omitempty"`
	// IdeaUserTitle holds the value of the "idea_user_title" field.
	IdeaUserTitle string `json:"idea_user_title,omitempty"`
	// IdeaUserCreatedAt holds the value of the "idea_user_created_at" field.
	IdeaUserCreatedAt *time.Time `json:"idea_user_created_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IdeaEndorsement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ideaendorsement.FieldWeight:
			values[i] = new(sql.NullInt64)
		case ideaendorsement.FieldID, ideaendorsement.FieldProduct, ideaendorsement.FieldIdeaID, ideaendorsement.FieldValue, ideaendorsement.FieldLink, ideaendorsement.FieldPortalUserID, ideaendorsement.FieldPortalUserName, ideaendorsement.FieldPortalUserEmail, ideaendorsement.FieldIdeaUserID, ideaendorsement.FieldIdeaUserName, ideaendorsement.FieldIdeaUserEmail, ideaendorsement.FieldIdeaUserTitle:
			values[i] = new(sql.NullString)
		case ideaendorsement.FieldPortalUserCreatedAt, ideaendorsement.FieldIdeaUserCreatedAt, ideaendorsement.FieldCreatedAt, ideaendorsement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IdeaEndorsement fields.
func (_m *IdeaEndorsement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ideaendorsement.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ideaendorsement.FieldProduct:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product", values[i])
			} else if value.Valid {
				_m.Product = value.String
			}
		case ideaendorsement.FieldIdeaID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idea_id", values[i])
			} else if value.Valid {
				_m.IdeaID = value.String
			}
		case ideaendorsement.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case ideaendorsement.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case ideaendorsement.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				_m.Link = value.String
			}
		case ideaendorsement.FieldPortalUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field portal_user_id", values[i])
			} else if value.Valid {
				_m.PortalUserID = value.String
			}
		case ideaendorsement.FieldPortalUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field portal_user_name", values[i])
			} else if value.Valid {
				_m.PortalUserName = value.String
			}
		case ideaendorsement.FieldPortalUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field portal_user_email", values[i])
			} else if value.Valid {
				_m.PortalUserEmail = value.String
			}
		case ideaendorsement.FieldPortalUserCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field portal_user_created_at", values[i])
			} else if value.Valid {
				_m.PortalUserCreatedAt = new(time.Time)
				*_m.PortalUserCreatedAt = value.Time
			}
		case ideaendorsement.FieldIdeaUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idea_user_id", values[i])
			} else if value.Valid {
				_m.IdeaUserID = value.String
			}
		case ideaendorsement.FieldIdeaUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idea_user_name", values[i])
			} else if value.Valid {
				_m.IdeaUserName = value.String
			}
		case ideaendorsement.FieldIdeaUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idea_user_email", values[i])
			} else if value.Valid {
				_m.IdeaUserEmail = value.String
			}
		case ideaendorsement.FieldIdeaUserTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idea_user_title", values[i])
			} else if value.Valid {
				_m.IdeaUserTitle = value.String
			}
		case ideaendorsement.FieldIdeaUserCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field idea_user_created_at", values[i])
			} else if value.Valid {
				_m.IdeaUserCreatedAt = new(time.Time)
				*_m.IdeaUserCreatedAt = value.Time
			}
		case ideaendorsement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case ideaendorsement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the IdeaEndorsement.
// This includes values selected through modifiers, order, etc.
func (_m *IdeaEndorsement) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IdeaEndorsement.
// Note that you need to call IdeaEndorsement.Unwrap() before calling this method if this IdeaEndorsement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IdeaEndorsement) Update() *IdeaEndorsementUpdateOne {
	return NewIdeaEndorsementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IdeaEndorsement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IdeaEndorsement) Unwrap() *IdeaEndorsement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IdeaEndorsement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IdeaEndorsement) String() string {
	var builder strings.Builder
	builder.WriteString("IdeaEndorsement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("product=")
	builder.WriteString(_m.Product)
	builder.WriteString(", ")
	builder.WriteString("idea_id=")
	builder.WriteString(_m.IdeaID)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(_m.Link)
	builder.WriteString(", ")
	builder.WriteString("portal_user_id=")
	builder.WriteString(_m.PortalUserID)
	builder.WriteString(", ")
	builder.WriteString("portal_user_name=")
	builder.WriteString(_m.PortalUserName)
	builder.WriteString(", ")
	builder.WriteString("portal_user_email=")
	builder.WriteString(_m.PortalUserEmail)
	builder.WriteString(", ")
	if v := _m.PortalUserCreatedAt; v != nil {
		builder.WriteString("portal_user_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("idea_user_id=")
	builder.WriteString(_m.IdeaUserID)
	builder.WriteString(", ")
	builder.WriteString("idea_user_name=")
	builder.WriteString(_m.IdeaUserName)
	builder.WriteString(", ")
	builder.WriteString("idea_user_email=")
	builder.WriteString(_m.IdeaUserEmail)
	builder.WriteString(", ")
	builder.WriteString("idea_user_title=")
	builder.WriteString(_m.IdeaUserTitle)
	builder.WriteString(", ")
	if v := _m.IdeaUserCreatedAt; v != nil {
		builder.WriteString("idea_user_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// IdeaEndorsements is a parsable slice of IdeaEndorsement.
type IdeaEndorsements []*IdeaEndorsement
