// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/ideaendorsement"
)

// IdeaEndorsementCreate is the builder for creating a IdeaEndorsement entity.
type IdeaEndorsementCreate struct {
	config
	mutation *IdeaEndorsementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProduct sets the "product" field.
func (_c *IdeaEndorsementCreate) SetProduct(v string) *IdeaEndorsementCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableProduct(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetProduct(*v)
	}
	return _c
}

// SetIdeaID sets the "idea_id" field.
func (_c *IdeaEndorsementCreate) SetIdeaID(v string) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaID(v)
	return _c
}

// SetNillableIdeaID sets the "idea_id" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaID(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaID(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *IdeaEndorsementCreate) SetWeight(v int) *IdeaEndorsementCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableWeight(v *int) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *IdeaEndorsementCreate) SetValue(v string) *IdeaEndorsementCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableValue(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetLink sets the "link" field.
func (_c *IdeaEndorsementCreate) SetLink(v string) *IdeaEndorsementCreate {
	_c.mutation.SetLink(v)
	return _c
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableLink(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetLink(*v)
	}
	return _c
}

// SetPortalUserID sets the "portal_user_id" field.
func (_c *IdeaEndorsementCreate) SetPortalUserID(v string) *IdeaEndorsementCreate {
	_c.mutation.SetPortalUserID(v)
	return _c
}

// SetNillablePortalUserID sets the "portal_user_id" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillablePortalUserID(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetPortalUserID(*v)
	}
	return _c
}

// SetPortalUserName sets the "portal_user_name" field.
func (_c *IdeaEndorsementCreate) SetPortalUserName(v string) *IdeaEndorsementCreate {
	_c.mutation.SetPortalUserName(v)
	return _c
}

// SetNillablePortalUserName sets the "portal_user_name" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillablePortalUserName(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetPortalUserName(*v)
	}
	return _c
}

// SetPortalUserEmail sets the "portal_user_email" field.
func (_c *IdeaEndorsementCreate) SetPortalUserEmail(v string) *IdeaEndorsementCreate {
	_c.mutation.SetPortalUserEmail(v)
	return _c
}

// SetNillablePortalUserEmail sets the "portal_user_email" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillablePortalUserEmail(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetPortalUserEmail(*v)
	}
	return _c
}

// SetPortalUserCreatedAt sets the "portal_user_created_at" field.
func (_c *IdeaEndorsementCreate) SetPortalUserCreatedAt(v time.Time) *IdeaEndorsementCreate {
	_c.mutation.SetPortalUserCreatedAt(v)
	return _c
}

// SetNillablePortalUserCreatedAt sets the "portal_user_created_at" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillablePortalUserCreatedAt(v *time.Time) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetPortalUserCreatedAt(*v)
	}
	return _c
}

// SetIdeaUserID sets the "idea_user_id" field.
func (_c *IdeaEndorsementCreate) SetIdeaUserID(v string) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaUserID(v)
	return _c
}

// SetNillableIdeaUserID sets the "idea_user_id" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaUserID(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaUserID(*v)
	}
	return _c
}

// SetIdeaUserName sets the "idea_user_name" field.
func (_c *IdeaEndorsementCreate) SetIdeaUserName(v string) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaUserName(v)
	return _c
}

// SetNillableIdeaUserName sets the "idea_user_name" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaUserName(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaUserName(*v)
	}
	return _c
}

// SetIdeaUserEmail sets the "idea_user_email" field.
func (_c *IdeaEndorsementCreate) SetIdeaUserEmail(v string) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaUserEmail(v)
	return _c
}

// SetNillableIdeaUserEmail sets the "idea_user_email" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaUserEmail(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaUserEmail(*v)
	}
	return _c
}

// SetIdeaUserTitle sets the "idea_user_title" field.
func (_c *IdeaEndorsementCreate) SetIdeaUserTitle(v string) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaUserTitle(v)
	return _c
}

// SetNillableIdeaUserTitle sets the "idea_user_title" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaUserTitle(v *string) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaUserTitle(*v)
	}
	return _c
}

// SetIdeaUserCreatedAt sets the "idea_user_created_at" field.
func (_c *IdeaEndorsementCreate) SetIdeaUserCreatedAt(v time.Time) *IdeaEndorsementCreate {
	_c.mutation.SetIdeaUserCreatedAt(v)
	return _c
}

// SetNillableIdeaUserCreatedAt sets the "idea_user_created_at" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableIdeaUserCreatedAt(v *time.Time) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetIdeaUserCreatedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdeaEndorsementCreate) SetCreatedAt(v time.Time) *IdeaEndorsementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableCreatedAt(v *time.Time) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IdeaEndorsementCreate) SetUpdatedAt(v time.Time) *IdeaEndorsementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IdeaEndorsementCreate) SetNillableUpdatedAt(v *time.Time) *IdeaEndorsementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IdeaEndorsementCreate) SetID(v string) *IdeaEndorsementCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IdeaEndorsementMutation object of the builder.
func (_c *IdeaEndorsementCreate) Mutation() *IdeaEndorsementMutation {
	return _c.mutation
}

// Save creates the IdeaEndorsement in the database.
func (_c *IdeaEndorsementCreate) Save(ctx context.Context) (*IdeaEndorsement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdeaEndorsementCreate) SaveX(ctx context.Context) *IdeaEndorsement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdeaEndorsementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdeaEndorsementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdeaEndorsementCreate) defaults() {
	if _, ok := _c.mutation.Weight(); !ok {
		v := ideaendorsement.DefaultWeight
		_c.mutation.SetWeight(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdeaEndorsementCreate) check() error {
	return nil
}

func (_c *IdeaEndorsementCreate) sqlSave(ctx context.Context) (*IdeaEndorsement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IdeaEndorsement.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdeaEndorsementCreate) createSpec() (*IdeaEndorsement, *sqlgraph.CreateSpec) {
	var (
		_node = &IdeaEndorsement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ideaendorsement.Table, sqlgraph.NewFieldSpec(ideaendorsement.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(ideaendorsement.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.IdeaID(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaID, field.TypeString, value)
		_node.IdeaID = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(ideaendorsement.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(ideaendorsement.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Link(); ok {
		_spec.SetField(ideaendorsement.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := _c.mutation.PortalUserID(); ok {
		_spec.SetField(ideaendorsement.FieldPortalUserID, field.TypeString, value)
		_node.PortalUserID = value
	}
	if value, ok := _c.mutation.PortalUserName(); ok {
		_spec.SetField(ideaendorsement.FieldPortalUserName, field.TypeString, value)
		_node.PortalUserName = value
	}
	if value, ok := _c.mutation.PortalUserEmail(); ok {
		_spec.SetField(ideaendorsement.FieldPortalUserEmail, field.TypeString, value)
		_node.PortalUserEmail = value
	}
	if value, ok := _c.mutation.PortalUserCreatedAt(); ok {
		_spec.SetField(ideaendorsement.FieldPortalUserCreatedAt, field.TypeTime, value)
		_node.PortalUserCreatedAt = &value
	}
	if value, ok := _c.mutation.IdeaUserID(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaUserID, field.TypeString, value)
		_node.IdeaUserID = value
	}
	if value, ok := _c.mutation.IdeaUserName(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaUserName, field.TypeString, value)
		_node.IdeaUserName = value
	}
	if value, ok := _c.mutation.IdeaUserEmail(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaUserEmail, field.TypeString, value)
		_node.IdeaUserEmail = value
	}
	if value, ok := _c.mutation.IdeaUserTitle(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaUserTitle, field.TypeString, value)
		_node.IdeaUserTitle = value
	}
	if value, ok := _c.mutation.IdeaUserCreatedAt(); ok {
		_spec.SetField(ideaendorsement.FieldIdeaUserCreatedAt, field.TypeTime, value)
		_node.IdeaUserCreatedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ideaendorsement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ideaendorsement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdeaEndorsement.Create().
//		SetProduct(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdeaEndorsementUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *IdeaEndorsementCreate) OnConflict(opts ...sql.ConflictOption) *IdeaEndorsementUpsertOne {
	_c.conflict = opts
	return &IdeaEndorsementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdeaEndorsementCreate) OnConflictColumns(columns ...string) *IdeaEndorsementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdeaEndorsementUpsertOne{
		create: _c,
	}
}

type (
	// IdeaEndorsementUpsertOne is the builder for "upsert"-ing
	//  one IdeaEndorsement node.
	IdeaEndorsementUpsertOne struct {
		create *IdeaEndorsementCreate
	}

	// IdeaEndorsementUpsert is the "OnConflict" setter.
	IdeaEndorsementUpsert struct {
		*sql.UpdateSet
	}
)

// SetProduct sets the "product" field.
func (u *IdeaEndorsementUpsert) SetProduct(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateProduct() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldProduct)
	return u
}

// ClearProduct clears the value of the "product" field.
func (u *IdeaEndorsementUpsert) ClearProduct() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldProduct)
	return u
}

// SetIdeaID sets the "idea_id" field.
func (u *IdeaEndorsementUpsert) SetIdeaID(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaID, v)
	return u
}

// UpdateIdeaID sets the "idea_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaID() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaID)
	return u
}

// ClearIdeaID clears the value of the "idea_id" field.
func (u *IdeaEndorsementUpsert) ClearIdeaID() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaID)
	return u
}

// SetWeight sets the "weight" field.
func (u *IdeaEndorsementUpsert) SetWeight(v int) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateWeight() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *IdeaEndorsementUpsert) AddWeight(v int) *IdeaEndorsementUpsert {
	u.Add(ideaendorsement.FieldWeight, v)
	return u
}

// ClearWeight clears the value of the "weight" field.
func (u *IdeaEndorsementUpsert) ClearWeight() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldWeight)
	return u
}

// SetValue sets the "value" field.
func (u *IdeaEndorsementUpsert) SetValue(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateValue() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldValue)
	return u
}

// ClearValue clears the value of the "value" field.
func (u *IdeaEndorsementUpsert) ClearValue() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldValue)
	return u
}

// SetLink sets the "link" field.
func (u *IdeaEndorsementUpsert) SetLink(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateLink() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldLink)
	return u
}

// ClearLink clears the value of the "link" field.
func (u *IdeaEndorsementUpsert) ClearLink() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldLink)
	return u
}

// SetPortalUserID sets the "portal_user_id" field.
func (u *IdeaEndorsementUpsert) SetPortalUserID(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldPortalUserID, v)
	return u
}

// UpdatePortalUserID sets the "portal_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdatePortalUserID() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldPortalUserID)
	return u
}

// ClearPortalUserID clears the value of the "portal_user_id" field.
func (u *IdeaEndorsementUpsert) ClearPortalUserID() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldPortalUserID)
	return u
}

// SetPortalUserName sets the "portal_user_name" field.
func (u *IdeaEndorsementUpsert) SetPortalUserName(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldPortalUserName, v)
	return u
}

// UpdatePortalUserName sets the "portal_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdatePortalUserName() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldPortalUserName)
	return u
}

// ClearPortalUserName clears the value of the "portal_user_name" field.
func (u *IdeaEndorsementUpsert) ClearPortalUserName() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldPortalUserName)
	return u
}

// SetPortalUserEmail sets the "portal_user_email" field.
func (u *IdeaEndorsementUpsert) SetPortalUserEmail(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldPortalUserEmail, v)
	return u
}

// UpdatePortalUserEmail sets the "portal_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdatePortalUserEmail() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldPortalUserEmail)
	return u
}

// ClearPortalUserEmail clears the value of the "portal_user_email" field.
func (u *IdeaEndorsementUpsert) ClearPortalUserEmail() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldPortalUserEmail)
	return u
}

// SetPortalUserCreatedAt sets the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsert) SetPortalUserCreatedAt(v time.Time) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldPortalUserCreatedAt, v)
	return u
}

// UpdatePortalUserCreatedAt sets the "portal_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdatePortalUserCreatedAt() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldPortalUserCreatedAt)
	return u
}

// ClearPortalUserCreatedAt clears the value of the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsert) ClearPortalUserCreatedAt() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldPortalUserCreatedAt)
	return u
}

// SetIdeaUserID sets the "idea_user_id" field.
func (u *IdeaEndorsementUpsert) SetIdeaUserID(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaUserID, v)
	return u
}

// UpdateIdeaUserID sets the "idea_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaUserID() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaUserID)
	return u
}

// ClearIdeaUserID clears the value of the "idea_user_id" field.
func (u *IdeaEndorsementUpsert) ClearIdeaUserID() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaUserID)
	return u
}

// SetIdeaUserName sets the "idea_user_name" field.
func (u *IdeaEndorsementUpsert) SetIdeaUserName(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaUserName, v)
	return u
}

// UpdateIdeaUserName sets the "idea_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaUserName() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaUserName)
	return u
}

// ClearIdeaUserName clears the value of the "idea_user_name" field.
func (u *IdeaEndorsementUpsert) ClearIdeaUserName() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaUserName)
	return u
}

// SetIdeaUserEmail sets the "idea_user_email" field.
func (u *IdeaEndorsementUpsert) SetIdeaUserEmail(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaUserEmail, v)
	return u
}

// UpdateIdeaUserEmail sets the "idea_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaUserEmail() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaUserEmail)
	return u
}

// ClearIdeaUserEmail clears the value of the "idea_user_email" field.
func (u *IdeaEndorsementUpsert) ClearIdeaUserEmail() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaUserEmail)
	return u
}

// SetIdeaUserTitle sets the "idea_user_title" field.
func (u *IdeaEndorsementUpsert) SetIdeaUserTitle(v string) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaUserTitle, v)
	return u
}

// UpdateIdeaUserTitle sets the "idea_user_title" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaUserTitle() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaUserTitle)
	return u
}

// ClearIdeaUserTitle clears the value of the "idea_user_title" field.
func (u *IdeaEndorsementUpsert) ClearIdeaUserTitle() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaUserTitle)
	return u
}

// SetIdeaUserCreatedAt sets the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsert) SetIdeaUserCreatedAt(v time.Time) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldIdeaUserCreatedAt, v)
	return u
}

// UpdateIdeaUserCreatedAt sets the "idea_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateIdeaUserCreatedAt() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldIdeaUserCreatedAt)
	return u
}

// ClearIdeaUserCreatedAt clears the value of the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsert) ClearIdeaUserCreatedAt() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldIdeaUserCreatedAt)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaEndorsementUpsert) SetCreatedAt(v time.Time) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateCreatedAt() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaEndorsementUpsert) ClearCreatedAt() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdeaEndorsementUpsert) SetUpdatedAt(v time.Time) *IdeaEndorsementUpsert {
	u.Set(ideaendorsement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsert) UpdateUpdatedAt() *IdeaEndorsementUpsert {
	u.SetExcluded(ideaendorsement.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IdeaEndorsementUpsert) ClearUpdatedAt() *IdeaEndorsementUpsert {
	u.SetNull(ideaendorsement.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ideaendorsement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdeaEndorsementUpsertOne) UpdateNewValues() *IdeaEndorsementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ideaendorsement.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IdeaEndorsementUpsertOne) Ignore() *IdeaEndorsementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdeaEndorsementUpsertOne) DoNothing() *IdeaEndorsementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdeaEndorsementCreate.OnConflict
// documentation for more info.
func (u *IdeaEndorsementUpsertOne) Update(set func(*IdeaEndorsementUpsert)) *IdeaEndorsementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdeaEndorsementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *IdeaEndorsementUpsertOne) SetProduct(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateProduct() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateProduct()
	})
}

// ClearProduct clears the value of the "product" field.
func (u *IdeaEndorsementUpsertOne) ClearProduct() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearProduct()
	})
}

// SetIdeaID sets the "idea_id" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaID(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaID(v)
	})
}

// UpdateIdeaID sets the "idea_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaID()
	})
}

// ClearIdeaID clears the value of the "idea_id" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaID()
	})
}

// SetWeight sets the "weight" field.
func (u *IdeaEndorsementUpsertOne) SetWeight(v int) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *IdeaEndorsementUpsertOne) AddWeight(v int) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateWeight() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateWeight()
	})
}

// ClearWeight clears the value of the "weight" field.
func (u *IdeaEndorsementUpsertOne) ClearWeight() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearWeight()
	})
}

// SetValue sets the "value" field.
func (u *IdeaEndorsementUpsertOne) SetValue(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateValue() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateValue()
	})
}

// ClearValue clears the value of the "value" field.
func (u *IdeaEndorsementUpsertOne) ClearValue() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearValue()
	})
}

// SetLink sets the "link" field.
func (u *IdeaEndorsementUpsertOne) SetLink(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateLink() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateLink()
	})
}

// ClearLink clears the value of the "link" field.
func (u *IdeaEndorsementUpsertOne) ClearLink() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearLink()
	})
}

// SetPortalUserID sets the "portal_user_id" field.
func (u *IdeaEndorsementUpsertOne) SetPortalUserID(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserID(v)
	})
}

// UpdatePortalUserID sets the "portal_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdatePortalUserID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserID()
	})
}

// ClearPortalUserID clears the value of the "portal_user_id" field.
func (u *IdeaEndorsementUpsertOne) ClearPortalUserID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserID()
	})
}

// SetPortalUserName sets the "portal_user_name" field.
func (u *IdeaEndorsementUpsertOne) SetPortalUserName(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserName(v)
	})
}

// UpdatePortalUserName sets the "portal_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdatePortalUserName() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserName()
	})
}

// ClearPortalUserName clears the value of the "portal_user_name" field.
func (u *IdeaEndorsementUpsertOne) ClearPortalUserName() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserName()
	})
}

// SetPortalUserEmail sets the "portal_user_email" field.
func (u *IdeaEndorsementUpsertOne) SetPortalUserEmail(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserEmail(v)
	})
}

// UpdatePortalUserEmail sets the "portal_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdatePortalUserEmail() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserEmail()
	})
}

// ClearPortalUserEmail clears the value of the "portal_user_email" field.
func (u *IdeaEndorsementUpsertOne) ClearPortalUserEmail() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserEmail()
	})
}

// SetPortalUserCreatedAt sets the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsertOne) SetPortalUserCreatedAt(v time.Time) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserCreatedAt(v)
	})
}

// UpdatePortalUserCreatedAt sets the "portal_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdatePortalUserCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserCreatedAt()
	})
}

// ClearPortalUserCreatedAt clears the value of the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsertOne) ClearPortalUserCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserCreatedAt()
	})
}

// SetIdeaUserID sets the "idea_user_id" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaUserID(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserID(v)
	})
}

// UpdateIdeaUserID sets the "idea_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaUserID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserID()
	})
}

// ClearIdeaUserID clears the value of the "idea_user_id" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaUserID() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserID()
	})
}

// SetIdeaUserName sets the "idea_user_name" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaUserName(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserName(v)
	})
}

// UpdateIdeaUserName sets the "idea_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaUserName() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserName()
	})
}

// ClearIdeaUserName clears the value of the "idea_user_name" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaUserName() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserName()
	})
}

// SetIdeaUserEmail sets the "idea_user_email" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaUserEmail(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserEmail(v)
	})
}

// UpdateIdeaUserEmail sets the "idea_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaUserEmail() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserEmail()
	})
}

// ClearIdeaUserEmail clears the value of the "idea_user_email" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaUserEmail() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserEmail()
	})
}

// SetIdeaUserTitle sets the "idea_user_title" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaUserTitle(v string) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserTitle(v)
	})
}

// UpdateIdeaUserTitle sets the "idea_user_title" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaUserTitle() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserTitle()
	})
}

// ClearIdeaUserTitle clears the value of the "idea_user_title" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaUserTitle() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserTitle()
	})
}

// SetIdeaUserCreatedAt sets the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsertOne) SetIdeaUserCreatedAt(v time.Time) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserCreatedAt(v)
	})
}

// UpdateIdeaUserCreatedAt sets the "idea_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateIdeaUserCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserCreatedAt()
	})
}

// ClearIdeaUserCreatedAt clears the value of the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsertOne) ClearIdeaUserCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserCreatedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaEndorsementUpsertOne) SetCreatedAt(v time.Time) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaEndorsementUpsertOne) ClearCreatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdeaEndorsementUpsertOne) SetUpdatedAt(v time.Time) *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertOne) UpdateUpdatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IdeaEndorsementUpsertOne) ClearUpdatedAt() *IdeaEndorsementUpsertOne {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *IdeaEndorsementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdeaEndorsementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdeaEndorsementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IdeaEndorsementUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IdeaEndorsementUpsertOne.ID is not supported by MySQL driver. Use IdeaEndorsementUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IdeaEndorsementUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IdeaEndorsementCreateBulk is the builder for creating many IdeaEndorsement entities in bulk.
type IdeaEndorsementCreateBulk struct {
	config
	err      error
	builders []*IdeaEndorsementCreate
	conflict []sql.ConflictOption
}

// Save creates the IdeaEndorsement entities in the database.
func (_c *IdeaEndorsementCreateBulk) Save(ctx context.Context) ([]*IdeaEndorsement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdeaEndorsement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdeaEndorsementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdeaEndorsementCreateBulk) SaveX(ctx context.Context) []*IdeaEndorsement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdeaEndorsementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdeaEndorsementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IdeaEndorsement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdeaEndorsementUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *IdeaEndorsementCreateBulk) OnConflict(opts ...sql.ConflictOption) *IdeaEndorsementUpsertBulk {
	_c.conflict = opts
	return &IdeaEndorsementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdeaEndorsementCreateBulk) OnConflictColumns(columns ...string) *IdeaEndorsementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdeaEndorsementUpsertBulk{
		create: _c,
	}
}

// IdeaEndorsementUpsertBulk is the builder for "upsert"-ing
// a bulk of IdeaEndorsement nodes.
type IdeaEndorsementUpsertBulk struct {
	create *IdeaEndorsementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ideaendorsement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdeaEndorsementUpsertBulk) UpdateNewValues() *IdeaEndorsementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ideaendorsement.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IdeaEndorsement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IdeaEndorsementUpsertBulk) Ignore() *IdeaEndorsementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdeaEndorsementUpsertBulk) DoNothing() *IdeaEndorsementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdeaEndorsementCreateBulk.OnConflict
// documentation for more info.
func (u *IdeaEndorsementUpsertBulk) Update(set func(*IdeaEndorsementUpsert)) *IdeaEndorsementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdeaEndorsementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *IdeaEndorsementUpsertBulk) SetProduct(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateProduct() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateProduct()
	})
}

// ClearProduct clears the value of the "product" field.
func (u *IdeaEndorsementUpsertBulk) ClearProduct() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearProduct()
	})
}

// SetIdeaID sets the "idea_id" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaID(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaID(v)
	})
}

// UpdateIdeaID sets the "idea_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaID()
	})
}

// ClearIdeaID clears the value of the "idea_id" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaID()
	})
}

// SetWeight sets the "weight" field.
func (u *IdeaEndorsementUpsertBulk) SetWeight(v int) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *IdeaEndorsementUpsertBulk) AddWeight(v int) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateWeight() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateWeight()
	})
}

// ClearWeight clears the value of the "weight" field.
func (u *IdeaEndorsementUpsertBulk) ClearWeight() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearWeight()
	})
}

// SetValue sets the "value" field.
func (u *IdeaEndorsementUpsertBulk) SetValue(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateValue() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateValue()
	})
}

// ClearValue clears the value of the "value" field.
func (u *IdeaEndorsementUpsertBulk) ClearValue() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearValue()
	})
}

// SetLink sets the "link" field.
func (u *IdeaEndorsementUpsertBulk) SetLink(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateLink() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateLink()
	})
}

// ClearLink clears the value of the "link" field.
func (u *IdeaEndorsementUpsertBulk) ClearLink() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearLink()
	})
}

// SetPortalUserID sets the "portal_user_id" field.
func (u *IdeaEndorsementUpsertBulk) SetPortalUserID(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserID(v)
	})
}

// UpdatePortalUserID sets the "portal_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdatePortalUserID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserID()
	})
}

// ClearPortalUserID clears the value of the "portal_user_id" field.
func (u *IdeaEndorsementUpsertBulk) ClearPortalUserID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserID()
	})
}

// SetPortalUserName sets the "portal_user_name" field.
func (u *IdeaEndorsementUpsertBulk) SetPortalUserName(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserName(v)
	})
}

// UpdatePortalUserName sets the "portal_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdatePortalUserName() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserName()
	})
}

// ClearPortalUserName clears the value of the "portal_user_name" field.
func (u *IdeaEndorsementUpsertBulk) ClearPortalUserName() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserName()
	})
}

// SetPortalUserEmail sets the "portal_user_email" field.
func (u *IdeaEndorsementUpsertBulk) SetPortalUserEmail(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserEmail(v)
	})
}

// UpdatePortalUserEmail sets the "portal_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdatePortalUserEmail() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserEmail()
	})
}

// ClearPortalUserEmail clears the value of the "portal_user_email" field.
func (u *IdeaEndorsementUpsertBulk) ClearPortalUserEmail() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserEmail()
	})
}

// SetPortalUserCreatedAt sets the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsertBulk) SetPortalUserCreatedAt(v time.Time) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetPortalUserCreatedAt(v)
	})
}

// UpdatePortalUserCreatedAt sets the "portal_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdatePortalUserCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdatePortalUserCreatedAt()
	})
}

// ClearPortalUserCreatedAt clears the value of the "portal_user_created_at" field.
func (u *IdeaEndorsementUpsertBulk) ClearPortalUserCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearPortalUserCreatedAt()
	})
}

// SetIdeaUserID sets the "idea_user_id" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaUserID(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserID(v)
	})
}

// UpdateIdeaUserID sets the "idea_user_id" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaUserID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserID()
	})
}

// ClearIdeaUserID clears the value of the "idea_user_id" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaUserID() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserID()
	})
}

// SetIdeaUserName sets the "idea_user_name" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaUserName(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserName(v)
	})
}

// UpdateIdeaUserName sets the "idea_user_name" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaUserName() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserName()
	})
}

// ClearIdeaUserName clears the value of the "idea_user_name" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaUserName() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserName()
	})
}

// SetIdeaUserEmail sets the "idea_user_email" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaUserEmail(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserEmail(v)
	})
}

// UpdateIdeaUserEmail sets the "idea_user_email" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaUserEmail() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserEmail()
	})
}

// ClearIdeaUserEmail clears the value of the "idea_user_email" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaUserEmail() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserEmail()
	})
}

// SetIdeaUserTitle sets the "idea_user_title" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaUserTitle(v string) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserTitle(v)
	})
}

// UpdateIdeaUserTitle sets the "idea_user_title" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaUserTitle() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserTitle()
	})
}

// ClearIdeaUserTitle clears the value of the "idea_user_title" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaUserTitle() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserTitle()
	})
}

// SetIdeaUserCreatedAt sets the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsertBulk) SetIdeaUserCreatedAt(v time.Time) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetIdeaUserCreatedAt(v)
	})
}

// UpdateIdeaUserCreatedAt sets the "idea_user_created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateIdeaUserCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateIdeaUserCreatedAt()
	})
}

// ClearIdeaUserCreatedAt clears the value of the "idea_user_created_at" field.
func (u *IdeaEndorsementUpsertBulk) ClearIdeaUserCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearIdeaUserCreatedAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdeaEndorsementUpsertBulk) SetCreatedAt(v time.Time) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *IdeaEndorsementUpsertBulk) ClearCreatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdeaEndorsementUpsertBulk) SetUpdatedAt(v time.Time) *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdeaEndorsementUpsertBulk) UpdateUpdatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *IdeaEndorsementUpsertBulk) ClearUpdatedAt() *IdeaEndorsementUpsertBulk {
	return u.Update(func(s *IdeaEndorsementUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *IdeaEndorsementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IdeaEndorsementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdeaEndorsementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdeaEndorsementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
