// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/relationship"
)

// Relationship is the model entity for the Relationship schema.
type Relationship struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FromType holds the value of the "from_type" field.
	FromType string `json:"from_type,omitempty"`
	// FromID holds the value of the "from_id" field.
	FromID string `json:"from_id,omitempty"`
	// RelType holds the value of the "rel_type" field.
	RelType string `json:"rel_type,omitempty"`
	// ToType holds the value of the "to_type" field.
	ToType string `json:"to_type,omitempty"`
	// ToID holds the value of the "to_id" field.
	ToID string `json:"to_id,omitempty"`
	// Product holds the value of the "product" field.
	Product string `json:"product,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Relationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			values[i] = new(sql.NullInt64)
		case relationship.FieldFromType, relationship.FieldFromID, relationship.FieldRelType, relationship.FieldToType, relationship.FieldToID, relationship.FieldProduct:
			values[i] = new(sql.NullString)
		case relationship.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Relationship fields.
func (_m *Relationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relationship.FieldFromType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_type", values[i])
			} else if value.Valid {
				_m.FromType = value.String
			}
		case relationship.FieldFromID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				_m.FromID = value.String
			}
		case relationship.FieldRelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rel_type", values[i])
			} else if value.Valid {
				_m.RelType = value.String
			}
		case relationship.FieldToType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_type", values[i])
			} else if value.Valid {
				_m.ToType = value.String
			}
		case relationship.FieldToID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_id", values[i])
			} else if value.Valid {
				_m.ToID = value.String
			}
		case relationship.FieldProduct:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product", values[i])
			} else if value.Valid {
				_m.Product = value.String
			}
		case relationship.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Relationship.
// This includes values selected through modifiers, order, etc.
func (_m *Relationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Relationship.
// Note that you need to call Relationship.Unwrap() before calling this method if this Relationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Relationship) Update() *RelationshipUpdateOne {
	return NewRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Relationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Relationship) Unwrap() *Relationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Relationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Relationship) String() string {
	var builder strings.Builder
	builder.WriteString("Relationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("from_type=")
	builder.WriteString(_m.FromType)
	builder.WriteString(", ")
	builder.WriteString("from_id=")
	builder.WriteString(_m.FromID)
	builder.WriteString(", ")
	builder.WriteString("rel_type=")
	builder.WriteString(_m.RelType)
	builder.WriteString(", ")
	builder.WriteString("to_type=")
	builder.WriteString(_m.ToType)
	builder.WriteString(", ")
	builder.WriteString("to_id=")
	builder.WriteString(_m.ToID)
	builder.WriteString(", ")
	builder.WriteString("product=")
	builder.WriteString(_m.Product)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Relationships is a parsable slice of Relationship.
type Relationships []*Relationship
