// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/requirement"
)

// Requirement is the model entity for the Requirement schema.
type Requirement struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Product holds the value of the "product" field.
	Product string `json:"product,omitempty"`
	// FeatureID holds the value of the "feature_id" field.
	FeatureID string `json:"feature_id,omitempty"`
	// ReferenceNum holds the value of the "reference_num" field.
	ReferenceNum string `json:"reference_num,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AssignedTo holds the value of the "assigned_to" field.
	AssignedTo string `json:"assigned_to,omitempty"`
	// Position holds the value of the "position" field.
	Position *int `json:"position,omitempty"`
	// OriginalEstimate holds the value of the "original_estimate" field.
	OriginalEstimate *float64 `json:"original_estimate,omitempty"`
	// RemainingEstimate holds the value of the "remaining_estimate" field.
	RemainingEstimate *float64 `json:"remaining_estimate,omitempty"`
	// WorkDone holds the value of the "work_done" field.
	WorkDone *float64 `json:"work_done,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Data holds the value of the "data" field.
	Data         map[string]interface{} `json:"data,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Requirement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requirement.FieldData:
			values[i] = new([]byte)
		case requirement.FieldOriginalEstimate, requirement.FieldRemainingEstimate, requirement.FieldWorkDone:
			values[i] = new(sql.NullFloat64)
		case requirement.FieldPosition:
			values[i] = new(sql.NullInt64)
		case requirement.FieldID, requirement.FieldProduct, requirement.FieldFeatureID, requirement.FieldReferenceNum, requirement.FieldName, requirement.FieldDescription, requirement.FieldStatus, requirement.FieldAssignedTo, requirement.FieldURL:
			values[i] = new(sql.NullString)
		case requirement.FieldCreatedAt, requirement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Requirement fields.
func (_m *Requirement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requirement.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case requirement.FieldProduct:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product", values[i])
			} else if value.Valid {
				_m.Product = value.String
			}
		case requirement.FieldFeatureID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field feature_id", values[i])
			} else if value.Valid {
				_m.FeatureID = value.String
			}
		case requirement.FieldReferenceNum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_num", values[i])
			} else if value.Valid {
				_m.ReferenceNum = value.String
			}
		case requirement.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case requirement.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case requirement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case requirement.FieldAssignedTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_to", values[i])
			} else if value.Valid {
				_m.AssignedTo = value.String
			}
		case requirement.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = new(int)
				*_m.Position = int(value.Int64)
			}
		case requirement.FieldOriginalEstimate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field original_estimate", values[i])
			} else if value.Valid {
				_m.OriginalEstimate = new(float64)
				*_m.OriginalEstimate = value.Float64
			}
		case requirement.FieldRemainingEstimate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_estimate", values[i])
			} else if value.Valid {
				_m.RemainingEstimate = new(float64)
				*_m.RemainingEstimate = value.Float64
			}
		case requirement.FieldWorkDone:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field work_done", values[i])
			} else if value.Valid {
				_m.WorkDone = new(float64)
				*_m.WorkDone = value.Float64
			}
		case requirement.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case requirement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case requirement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case requirement.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Data); err != nil {
					return fmt.Errorf("unmarshal field data: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Requirement.
// This includes values selected through modifiers, order, etc.
func (_m *Requirement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Requirement.
// Note that you need to call Requirement.Unwrap() before calling this method if this Requirement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Requirement) Update() *RequirementUpdateOne {
	return NewRequirementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Requirement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Requirement) Unwrap() *Requirement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Requirement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Requirement) String() string {
	var builder strings.Builder
	builder.WriteString("Requirement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("product=")
	builder.WriteString(_m.Product)
	builder.WriteString(", ")
	builder.WriteString("feature_id=")
	builder.WriteString(_m.FeatureID)
	builder.WriteString(", ")
	builder.WriteString("reference_num=")
	builder.WriteString(_m.ReferenceNum)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("assigned_to=")
	builder.WriteString(_m.AssignedTo)
	builder.WriteString(", ")
	if v := _m.Position; v != nil {
		builder.WriteString("position=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OriginalEstimate; v != nil {
		builder.WriteString("original_estimate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RemainingEstimate; v != nil {
		builder.WriteString("remaining_estimate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WorkDone; v != nil {
		builder.WriteString("work_done=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteByte(')')
	return builder.String()
}

// Requirements is a parsable slice of Requirement.
type Requirements []*Requirement
