// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/requirement"
)

// RequirementCreate is the builder for creating a Requirement entity.
type RequirementCreate struct {
	config
	mutation *RequirementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProduct sets the "product" field.
func (_c *RequirementCreate) SetProduct(v string) *RequirementCreate {
	_c.mutation.SetProduct(v)
	return _c
}

// SetFeatureID sets the "feature_id" field.
func (_c *RequirementCreate) SetFeatureID(v string) *RequirementCreate {
	_c.mutation.SetFeatureID(v)
	return _c
}

// SetNillableFeatureID sets the "feature_id" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableFeatureID(v *string) *RequirementCreate {
	if v != nil {
		_c.SetFeatureID(*v)
	}
	return _c
}

// SetReferenceNum sets the "reference_num" field.
func (_c *RequirementCreate) SetReferenceNum(v string) *RequirementCreate {
	_c.mutation.SetReferenceNum(v)
	return _c
}

// SetNillableReferenceNum sets the "reference_num" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableReferenceNum(v *string) *RequirementCreate {
	if v != nil {
		_c.SetReferenceNum(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RequirementCreate) SetName(v string) *RequirementCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableName(v *string) *RequirementCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RequirementCreate) SetDescription(v string) *RequirementCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableDescription(v *string) *RequirementCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequirementCreate) SetStatus(v string) *RequirementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableStatus(v *string) *RequirementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssignedTo sets the "assigned_to" field.
func (_c *RequirementCreate) SetAssignedTo(v string) *RequirementCreate {
	_c.mutation.SetAssignedTo(v)
	return _c
}

// SetNillableAssignedTo sets the "assigned_to" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableAssignedTo(v *string) *RequirementCreate {
	if v != nil {
		_c.SetAssignedTo(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *RequirementCreate) SetPosition(v int) *RequirementCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *RequirementCreate) SetNillablePosition(v *int) *RequirementCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetOriginalEstimate sets the "original_estimate" field.
func (_c *RequirementCreate) SetOriginalEstimate(v float64) *RequirementCreate {
	_c.mutation.SetOriginalEstimate(v)
	return _c
}

// SetNillableOriginalEstimate sets the "original_estimate" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableOriginalEstimate(v *float64) *RequirementCreate {
	if v != nil {
		_c.SetOriginalEstimate(*v)
	}
	return _c
}

// SetRemainingEstimate sets the "remaining_estimate" field.
func (_c *RequirementCreate) SetRemainingEstimate(v float64) *RequirementCreate {
	_c.mutation.SetRemainingEstimate(v)
	return _c
}

// SetNillableRemainingEstimate sets the "remaining_estimate" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableRemainingEstimate(v *float64) *RequirementCreate {
	if v != nil {
		_c.SetRemainingEstimate(*v)
	}
	return _c
}

// SetWorkDone sets the "work_done" field.
func (_c *RequirementCreate) SetWorkDone(v float64) *RequirementCreate {
	_c.mutation.SetWorkDone(v)
	return _c
}

// SetNillableWorkDone sets the "work_done" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableWorkDone(v *float64) *RequirementCreate {
	if v != nil {
		_c.SetWorkDone(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *RequirementCreate) SetURL(v string) *RequirementCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableURL(v *string) *RequirementCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequirementCreate) SetCreatedAt(v time.Time) *RequirementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableCreatedAt(v *time.Time) *RequirementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequirementCreate) SetUpdatedAt(v time.Time) *RequirementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequirementCreate) SetNillableUpdatedAt(v *time.Time) *RequirementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetData sets the "data" field.
func (_c *RequirementCreate) SetData(v map[string]interface{}) *RequirementCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RequirementCreate) SetID(v string) *RequirementCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RequirementMutation object of the builder.
func (_c *RequirementCreate) Mutation() *RequirementMutation {
	return _c.mutation
}

// Save creates the Requirement in the database.
func (_c *RequirementCreate) Save(ctx context.Context) (*Requirement, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequirementCreate) SaveX(ctx context.Context) *Requirement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequirementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequirementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequirementCreate) check() error {
	if _, ok := _c.mutation.Product(); !ok {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required field "Requirement.product"`)}
	}
	return nil
}

func (_c *RequirementCreate) sqlSave(ctx context.Context) (*Requirement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Requirement.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequirementCreate) createSpec() (*Requirement, *sqlgraph.CreateSpec) {
	var (
		_node = &Requirement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requirement.Table, sqlgraph.NewFieldSpec(requirement.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Product(); ok {
		_spec.SetField(requirement.FieldProduct, field.TypeString, value)
		_node.Product = value
	}
	if value, ok := _c.mutation.FeatureID(); ok {
		_spec.SetField(requirement.FieldFeatureID, field.TypeString, value)
		_node.FeatureID = value
	}
	if value, ok := _c.mutation.ReferenceNum(); ok {
		_spec.SetField(requirement.FieldReferenceNum, field.TypeString, value)
		_node.ReferenceNum = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(requirement.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(requirement.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(requirement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedTo(); ok {
		_spec.SetField(requirement.FieldAssignedTo, field.TypeString, value)
		_node.AssignedTo = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(requirement.FieldPosition, field.TypeInt, value)
		_node.Position = &value
	}
	if value, ok := _c.mutation.OriginalEstimate(); ok {
		_spec.SetField(requirement.FieldOriginalEstimate, field.TypeFloat64, value)
		_node.OriginalEstimate = &value
	}
	if value, ok := _c.mutation.RemainingEstimate(); ok {
		_spec.SetField(requirement.FieldRemainingEstimate, field.TypeFloat64, value)
		_node.RemainingEstimate = &value
	}
	if value, ok := _c.mutation.WorkDone(); ok {
		_spec.SetField(requirement.FieldWorkDone, field.TypeFloat64, value)
		_node.WorkDone = &value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(requirement.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requirement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requirement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(requirement.FieldData, field.TypeJSON, value)
		_node.Data = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Requirement.Create().
//		SetProduct(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequirementUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *RequirementCreate) OnConflict(opts ...sql.ConflictOption) *RequirementUpsertOne {
	_c.conflict = opts
	return &RequirementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Requirement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequirementCreate) OnConflictColumns(columns ...string) *RequirementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequirementUpsertOne{
		create: _c,
	}
}

type (
	// RequirementUpsertOne is the builder for "upsert"-ing
	//  one Requirement node.
	RequirementUpsertOne struct {
		create *RequirementCreate
	}

	// RequirementUpsert is the "OnConflict" setter.
	RequirementUpsert struct {
		*sql.UpdateSet
	}
)

// SetProduct sets the "product" field.
func (u *RequirementUpsert) SetProduct(v string) *RequirementUpsert {
	u.Set(requirement.FieldProduct, v)
	return u
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateProduct() *RequirementUpsert {
	u.SetExcluded(requirement.FieldProduct)
	return u
}

// SetFeatureID sets the "feature_id" field.
func (u *RequirementUpsert) SetFeatureID(v string) *RequirementUpsert {
	u.Set(requirement.FieldFeatureID, v)
	return u
}

// UpdateFeatureID sets the "feature_id" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateFeatureID() *RequirementUpsert {
	u.SetExcluded(requirement.FieldFeatureID)
	return u
}

// ClearFeatureID clears the value of the "feature_id" field.
func (u *RequirementUpsert) ClearFeatureID() *RequirementUpsert {
	u.SetNull(requirement.FieldFeatureID)
	return u
}

// SetReferenceNum sets the "reference_num" field.
func (u *RequirementUpsert) SetReferenceNum(v string) *RequirementUpsert {
	u.Set(requirement.FieldReferenceNum, v)
	return u
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateReferenceNum() *RequirementUpsert {
	u.SetExcluded(requirement.FieldReferenceNum)
	return u
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *RequirementUpsert) ClearReferenceNum() *RequirementUpsert {
	u.SetNull(requirement.FieldReferenceNum)
	return u
}

// SetName sets the "name" field.
func (u *RequirementUpsert) SetName(v string) *RequirementUpsert {
	u.Set(requirement.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateName() *RequirementUpsert {
	u.SetExcluded(requirement.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *RequirementUpsert) ClearName() *RequirementUpsert {
	u.SetNull(requirement.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *RequirementUpsert) SetDescription(v string) *RequirementUpsert {
	u.Set(requirement.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateDescription() *RequirementUpsert {
	u.SetExcluded(requirement.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *RequirementUpsert) ClearDescription() *RequirementUpsert {
	u.SetNull(requirement.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *RequirementUpsert) SetStatus(v string) *RequirementUpsert {
	u.Set(requirement.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateStatus() *RequirementUpsert {
	u.SetExcluded(requirement.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *RequirementUpsert) ClearStatus() *RequirementUpsert {
	u.SetNull(requirement.FieldStatus)
	return u
}

// SetAssignedTo sets the "assigned_to" field.
func (u *RequirementUpsert) SetAssignedTo(v string) *RequirementUpsert {
	u.Set(requirement.FieldAssignedTo, v)
	return u
}

// UpdateAssignedTo sets the "assigned_to" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateAssignedTo() *RequirementUpsert {
	u.SetExcluded(requirement.FieldAssignedTo)
	return u
}

// ClearAssignedTo clears the value of the "assigned_to" field.
func (u *RequirementUpsert) ClearAssignedTo() *RequirementUpsert {
	u.SetNull(requirement.FieldAssignedTo)
	return u
}

// SetPosition sets the "position" field.
func (u *RequirementUpsert) SetPosition(v int) *RequirementUpsert {
	u.Set(requirement.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *RequirementUpsert) UpdatePosition() *RequirementUpsert {
	u.SetExcluded(requirement.FieldPosition)
	return u
}

// AddPosition adds v to the "position" field.
func (u *RequirementUpsert) AddPosition(v int) *RequirementUpsert {
	u.Add(requirement.FieldPosition, v)
	return u
}

// ClearPosition clears the value of the "position" field.
func (u *RequirementUpsert) ClearPosition() *RequirementUpsert {
	u.SetNull(requirement.FieldPosition)
	return u
}

// SetOriginalEstimate sets the "original_estimate" field.
func (u *RequirementUpsert) SetOriginalEstimate(v float64) *RequirementUpsert {
	u.Set(requirement.FieldOriginalEstimate, v)
	return u
}

// UpdateOriginalEstimate sets the "original_estimate" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateOriginalEstimate() *RequirementUpsert {
	u.SetExcluded(requirement.FieldOriginalEstimate)
	return u
}

// AddOriginalEstimate adds v to the "original_estimate" field.
func (u *RequirementUpsert) AddOriginalEstimate(v float64) *RequirementUpsert {
	u.Add(requirement.FieldOriginalEstimate, v)
	return u
}

// ClearOriginalEstimate clears the value of the "original_estimate" field.
func (u *RequirementUpsert) ClearOriginalEstimate() *RequirementUpsert {
	u.SetNull(requirement.FieldOriginalEstimate)
	return u
}

// SetRemainingEstimate sets the "remaining_estimate" field.
func (u *RequirementUpsert) SetRemainingEstimate(v float64) *RequirementUpsert {
	u.Set(requirement.FieldRemainingEstimate, v)
	return u
}

// UpdateRemainingEstimate sets the "remaining_estimate" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateRemainingEstimate() *RequirementUpsert {
	u.SetExcluded(requirement.FieldRemainingEstimate)
	return u
}

// AddRemainingEstimate adds v to the "remaining_estimate" field.
func (u *RequirementUpsert) AddRemainingEstimate(v float64) *RequirementUpsert {
	u.Add(requirement.FieldRemainingEstimate, v)
	return u
}

// ClearRemainingEstimate clears the value of the "remaining_estimate" field.
func (u *RequirementUpsert) ClearRemainingEstimate() *RequirementUpsert {
	u.SetNull(requirement.FieldRemainingEstimate)
	return u
}

// SetWorkDone sets the "work_done" field.
func (u *RequirementUpsert) SetWorkDone(v float64) *RequirementUpsert {
	u.Set(requirement.FieldWorkDone, v)
	return u
}

// UpdateWorkDone sets the "work_done" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateWorkDone() *RequirementUpsert {
	u.SetExcluded(requirement.FieldWorkDone)
	return u
}

// AddWorkDone adds v to the "work_done" field.
func (u *RequirementUpsert) AddWorkDone(v float64) *RequirementUpsert {
	u.Add(requirement.FieldWorkDone, v)
	return u
}

// ClearWorkDone clears the value of the "work_done" field.
func (u *RequirementUpsert) ClearWorkDone() *RequirementUpsert {
	u.SetNull(requirement.FieldWorkDone)
	return u
}

// SetURL sets the "url" field.
func (u *RequirementUpsert) SetURL(v string) *RequirementUpsert {
	u.Set(requirement.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateURL() *RequirementUpsert {
	u.SetExcluded(requirement.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *RequirementUpsert) ClearURL() *RequirementUpsert {
	u.SetNull(requirement.FieldURL)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RequirementUpsert) SetCreatedAt(v time.Time) *RequirementUpsert {
	u.Set(requirement.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateCreatedAt() *RequirementUpsert {
	u.SetExcluded(requirement.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *RequirementUpsert) ClearCreatedAt() *RequirementUpsert {
	u.SetNull(requirement.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequirementUpsert) SetUpdatedAt(v time.Time) *RequirementUpsert {
	u.Set(requirement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateUpdatedAt() *RequirementUpsert {
	u.SetExcluded(requirement.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RequirementUpsert) ClearUpdatedAt() *RequirementUpsert {
	u.SetNull(requirement.FieldUpdatedAt)
	return u
}

// SetData sets the "data" field.
func (u *RequirementUpsert) SetData(v map[string]interface{}) *RequirementUpsert {
	u.Set(requirement.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *RequirementUpsert) UpdateData() *RequirementUpsert {
	u.SetExcluded(requirement.FieldData)
	return u
}

// ClearData clears the value of the "data" field.
func (u *RequirementUpsert) ClearData() *RequirementUpsert {
	u.SetNull(requirement.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Requirement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(requirement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequirementUpsertOne) UpdateNewValues() *RequirementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(requirement.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Requirement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RequirementUpsertOne) Ignore() *RequirementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequirementUpsertOne) DoNothing() *RequirementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequirementCreate.OnConflict
// documentation for more info.
func (u *RequirementUpsertOne) Update(set func(*RequirementUpsert)) *RequirementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequirementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *RequirementUpsertOne) SetProduct(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateProduct() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateProduct()
	})
}

// SetFeatureID sets the "feature_id" field.
func (u *RequirementUpsertOne) SetFeatureID(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetFeatureID(v)
	})
}

// UpdateFeatureID sets the "feature_id" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateFeatureID() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateFeatureID()
	})
}

// ClearFeatureID clears the value of the "feature_id" field.
func (u *RequirementUpsertOne) ClearFeatureID() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearFeatureID()
	})
}

// SetReferenceNum sets the "reference_num" field.
func (u *RequirementUpsertOne) SetReferenceNum(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetReferenceNum(v)
	})
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateReferenceNum() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateReferenceNum()
	})
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *RequirementUpsertOne) ClearReferenceNum() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearReferenceNum()
	})
}

// SetName sets the "name" field.
func (u *RequirementUpsertOne) SetName(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateName() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *RequirementUpsertOne) ClearName() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *RequirementUpsertOne) SetDescription(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateDescription() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RequirementUpsertOne) ClearDescription() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *RequirementUpsertOne) SetStatus(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateStatus() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *RequirementUpsertOne) ClearStatus() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearStatus()
	})
}

// SetAssignedTo sets the "assigned_to" field.
func (u *RequirementUpsertOne) SetAssignedTo(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetAssignedTo(v)
	})
}

// UpdateAssignedTo sets the "assigned_to" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateAssignedTo() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateAssignedTo()
	})
}

// ClearAssignedTo clears the value of the "assigned_to" field.
func (u *RequirementUpsertOne) ClearAssignedTo() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearAssignedTo()
	})
}

// SetPosition sets the "position" field.
func (u *RequirementUpsertOne) SetPosition(v int) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *RequirementUpsertOne) AddPosition(v int) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdatePosition() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdatePosition()
	})
}

// ClearPosition clears the value of the "position" field.
func (u *RequirementUpsertOne) ClearPosition() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearPosition()
	})
}

// SetOriginalEstimate sets the "original_estimate" field.
func (u *RequirementUpsertOne) SetOriginalEstimate(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetOriginalEstimate(v)
	})
}

// AddOriginalEstimate adds v to the "original_estimate" field.
func (u *RequirementUpsertOne) AddOriginalEstimate(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.AddOriginalEstimate(v)
	})
}

// UpdateOriginalEstimate sets the "original_estimate" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateOriginalEstimate() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateOriginalEstimate()
	})
}

// ClearOriginalEstimate clears the value of the "original_estimate" field.
func (u *RequirementUpsertOne) ClearOriginalEstimate() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearOriginalEstimate()
	})
}

// SetRemainingEstimate sets the "remaining_estimate" field.
func (u *RequirementUpsertOne) SetRemainingEstimate(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetRemainingEstimate(v)
	})
}

// AddRemainingEstimate adds v to the "remaining_estimate" field.
func (u *RequirementUpsertOne) AddRemainingEstimate(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.AddRemainingEstimate(v)
	})
}

// UpdateRemainingEstimate sets the "remaining_estimate" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateRemainingEstimate() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateRemainingEstimate()
	})
}

// ClearRemainingEstimate clears the value of the "remaining_estimate" field.
func (u *RequirementUpsertOne) ClearRemainingEstimate() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearRemainingEstimate()
	})
}

// SetWorkDone sets the "work_done" field.
func (u *RequirementUpsertOne) SetWorkDone(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetWorkDone(v)
	})
}

// AddWorkDone adds v to the "work_done" field.
func (u *RequirementUpsertOne) AddWorkDone(v float64) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.AddWorkDone(v)
	})
}

// UpdateWorkDone sets the "work_done" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateWorkDone() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateWorkDone()
	})
}

// ClearWorkDone clears the value of the "work_done" field.
func (u *RequirementUpsertOne) ClearWorkDone() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearWorkDone()
	})
}

// SetURL sets the "url" field.
func (u *RequirementUpsertOne) SetURL(v string) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateURL() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *RequirementUpsertOne) ClearURL() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearURL()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RequirementUpsertOne) SetCreatedAt(v time.Time) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateCreatedAt() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *RequirementUpsertOne) ClearCreatedAt() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequirementUpsertOne) SetUpdatedAt(v time.Time) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateUpdatedAt() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RequirementUpsertOne) ClearUpdatedAt() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetData sets the "data" field.
func (u *RequirementUpsertOne) SetData(v map[string]interface{}) *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *RequirementUpsertOne) UpdateData() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *RequirementUpsertOne) ClearData() *RequirementUpsertOne {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *RequirementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequirementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequirementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequirementUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RequirementUpsertOne.ID is not supported by MySQL driver. Use RequirementUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequirementUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequirementCreateBulk is the builder for creating many Requirement entities in bulk.
type RequirementCreateBulk struct {
	config
	err      error
	builders []*RequirementCreate
	conflict []sql.ConflictOption
}

// Save creates the Requirement entities in the database.
func (_c *RequirementCreateBulk) Save(ctx context.Context) ([]*Requirement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Requirement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequirementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequirementCreateBulk) SaveX(ctx context.Context) []*Requirement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequirementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequirementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Requirement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequirementUpsert) {
//			SetProduct(v+v).
//		}).
//		Exec(ctx)
func (_c *RequirementCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequirementUpsertBulk {
	_c.conflict = opts
	return &RequirementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Requirement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RequirementCreateBulk) OnConflictColumns(columns ...string) *RequirementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RequirementUpsertBulk{
		create: _c,
	}
}

// RequirementUpsertBulk is the builder for "upsert"-ing
// a bulk of Requirement nodes.
type RequirementUpsertBulk struct {
	create *RequirementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Requirement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(requirement.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RequirementUpsertBulk) UpdateNewValues() *RequirementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(requirement.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Requirement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RequirementUpsertBulk) Ignore() *RequirementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequirementUpsertBulk) DoNothing() *RequirementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequirementCreateBulk.OnConflict
// documentation for more info.
func (u *RequirementUpsertBulk) Update(set func(*RequirementUpsert)) *RequirementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequirementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProduct sets the "product" field.
func (u *RequirementUpsertBulk) SetProduct(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetProduct(v)
	})
}

// UpdateProduct sets the "product" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateProduct() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateProduct()
	})
}

// SetFeatureID sets the "feature_id" field.
func (u *RequirementUpsertBulk) SetFeatureID(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetFeatureID(v)
	})
}

// UpdateFeatureID sets the "feature_id" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateFeatureID() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateFeatureID()
	})
}

// ClearFeatureID clears the value of the "feature_id" field.
func (u *RequirementUpsertBulk) ClearFeatureID() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearFeatureID()
	})
}

// SetReferenceNum sets the "reference_num" field.
func (u *RequirementUpsertBulk) SetReferenceNum(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetReferenceNum(v)
	})
}

// UpdateReferenceNum sets the "reference_num" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateReferenceNum() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateReferenceNum()
	})
}

// ClearReferenceNum clears the value of the "reference_num" field.
func (u *RequirementUpsertBulk) ClearReferenceNum() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearReferenceNum()
	})
}

// SetName sets the "name" field.
func (u *RequirementUpsertBulk) SetName(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateName() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *RequirementUpsertBulk) ClearName() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearName()
	})
}

// SetDescription sets the "description" field.
func (u *RequirementUpsertBulk) SetDescription(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateDescription() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RequirementUpsertBulk) ClearDescription() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *RequirementUpsertBulk) SetStatus(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateStatus() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *RequirementUpsertBulk) ClearStatus() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearStatus()
	})
}

// SetAssignedTo sets the "assigned_to" field.
func (u *RequirementUpsertBulk) SetAssignedTo(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetAssignedTo(v)
	})
}

// UpdateAssignedTo sets the "assigned_to" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateAssignedTo() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateAssignedTo()
	})
}

// ClearAssignedTo clears the value of the "assigned_to" field.
func (u *RequirementUpsertBulk) ClearAssignedTo() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearAssignedTo()
	})
}

// SetPosition sets the "position" field.
func (u *RequirementUpsertBulk) SetPosition(v int) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *RequirementUpsertBulk) AddPosition(v int) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdatePosition() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdatePosition()
	})
}

// ClearPosition clears the value of the "position" field.
func (u *RequirementUpsertBulk) ClearPosition() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearPosition()
	})
}

// SetOriginalEstimate sets the "original_estimate" field.
func (u *RequirementUpsertBulk) SetOriginalEstimate(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetOriginalEstimate(v)
	})
}

// AddOriginalEstimate adds v to the "original_estimate" field.
func (u *RequirementUpsertBulk) AddOriginalEstimate(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.AddOriginalEstimate(v)
	})
}

// UpdateOriginalEstimate sets the "original_estimate" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateOriginalEstimate() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateOriginalEstimate()
	})
}

// ClearOriginalEstimate clears the value of the "original_estimate" field.
func (u *RequirementUpsertBulk) ClearOriginalEstimate() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearOriginalEstimate()
	})
}

// SetRemainingEstimate sets the "remaining_estimate" field.
func (u *RequirementUpsertBulk) SetRemainingEstimate(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetRemainingEstimate(v)
	})
}

// AddRemainingEstimate adds v to the "remaining_estimate" field.
func (u *RequirementUpsertBulk) AddRemainingEstimate(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.AddRemainingEstimate(v)
	})
}

// UpdateRemainingEstimate sets the "remaining_estimate" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateRemainingEstimate() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateRemainingEstimate()
	})
}

// ClearRemainingEstimate clears the value of the "remaining_estimate" field.
func (u *RequirementUpsertBulk) ClearRemainingEstimate() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearRemainingEstimate()
	})
}

// SetWorkDone sets the "work_done" field.
func (u *RequirementUpsertBulk) SetWorkDone(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetWorkDone(v)
	})
}

// AddWorkDone adds v to the "work_done" field.
func (u *RequirementUpsertBulk) AddWorkDone(v float64) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.AddWorkDone(v)
	})
}

// UpdateWorkDone sets the "work_done" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateWorkDone() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateWorkDone()
	})
}

// ClearWorkDone clears the value of the "work_done" field.
func (u *RequirementUpsertBulk) ClearWorkDone() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearWorkDone()
	})
}

// SetURL sets the "url" field.
func (u *RequirementUpsertBulk) SetURL(v string) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateURL() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *RequirementUpsertBulk) ClearURL() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearURL()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RequirementUpsertBulk) SetCreatedAt(v time.Time) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateCreatedAt() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *RequirementUpsertBulk) ClearCreatedAt() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequirementUpsertBulk) SetUpdatedAt(v time.Time) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateUpdatedAt() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *RequirementUpsertBulk) ClearUpdatedAt() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetData sets the "data" field.
func (u *RequirementUpsertBulk) SetData(v map[string]interface{}) *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *RequirementUpsertBulk) UpdateData() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *RequirementUpsertBulk) ClearData() *RequirementUpsertBulk {
	return u.Update(func(s *RequirementUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *RequirementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequirementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequirementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequirementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
