// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/grokify/aha-studio/ent/predicate"
	"github.com/grokify/aha-studio/ent/syncmeta"
)

// SyncMetaUpdate is the builder for updating SyncMeta entities.
type SyncMetaUpdate struct {
	config
	hooks    []Hook
	mutation *SyncMetaMutation
}

// Where appends a list predicates to the SyncMetaUpdate builder.
func (_u *SyncMetaUpdate) Where(ps ...predicate.SyncMeta) *SyncMetaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntity sets the "entity" field.
func (_u *SyncMetaUpdate) SetEntity(v string) *SyncMetaUpdate {
	_u.mutation.SetEntity(v)
	return _u
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (_u *SyncMetaUpdate) SetNillableEntity(v *string) *SyncMetaUpdate {
	if v != nil {
		_u.SetEntity(*v)
	}
	return _u
}

// SetProduct sets the "product" field.
func (_u *SyncMetaUpdate) SetProduct(v string) *SyncMetaUpdate {
	_u.mutation.SetProduct(v)
	return _u
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_u *SyncMetaUpdate) SetNillableProduct(v *string) *SyncMetaUpdate {
	if v != nil {
		_u.SetProduct(*v)
	}
	return _u
}

// SetLastSync sets the "last_sync" field.
func (_u *SyncMetaUpdate) SetLastSync(v time.Time) *SyncMetaUpdate {
	_u.mutation.SetLastSync(v)
	return _u
}

// SetNillableLastSync sets the "last_sync" field if the given value is not nil.
func (_u *SyncMetaUpdate) SetNillableLastSync(v *time.Time) *SyncMetaUpdate {
	if v != nil {
		_u.SetLastSync(*v)
	}
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *SyncMetaUpdate) SetRecordCount(v int) *SyncMetaUpdate {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *SyncMetaUpdate) SetNillableRecordCount(v *int) *SyncMetaUpdate {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *SyncMetaUpdate) AddRecordCount(v int) *SyncMetaUpdate {
	_u.mutation.AddRecordCount(v)
	return _u
}

// ClearRecordCount clears the value of the "record_count" field.
func (_u *SyncMetaUpdate) ClearRecordCount() *SyncMetaUpdate {
	_u.mutation.ClearRecordCount()
	return _u
}

// Mutation returns the SyncMetaMutation object of the builder.
func (_u *SyncMetaUpdate) Mutation() *SyncMetaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncMetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncMetaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncMetaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncMetaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncmeta.Table, syncmeta.Columns, sqlgraph.NewFieldSpec(syncmeta.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Entity(); ok {
		_spec.SetField(syncmeta.FieldEntity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Product(); ok {
		_spec.SetField(syncmeta.FieldProduct, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSync(); ok {
		_spec.SetField(syncmeta.FieldLastSync, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(syncmeta.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(syncmeta.FieldRecordCount, field.TypeInt, value)
	}
	if _u.mutation.RecordCountCleared() {
		_spec.ClearField(syncmeta.FieldRecordCount, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncmeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncMetaUpdateOne is the builder for updating a single SyncMeta entity.
type SyncMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncMetaMutation
}

// SetEntity sets the "entity" field.
func (_u *SyncMetaUpdateOne) SetEntity(v string) *SyncMetaUpdateOne {
	_u.mutation.SetEntity(v)
	return _u
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (_u *SyncMetaUpdateOne) SetNillableEntity(v *string) *SyncMetaUpdateOne {
	if v != nil {
		_u.SetEntity(*v)
	}
	return _u
}

// SetProduct sets the "product" field.
func (_u *SyncMetaUpdateOne) SetProduct(v string) *SyncMetaUpdateOne {
	_u.mutation.SetProduct(v)
	return _u
}

// SetNillableProduct sets the "product" field if the given value is not nil.
func (_u *SyncMetaUpdateOne) SetNillableProduct(v *string) *SyncMetaUpdateOne {
	if v != nil {
		_u.SetProduct(*v)
	}
	return _u
}

// SetLastSync sets the "last_sync" field.
func (_u *SyncMetaUpdateOne) SetLastSync(v time.Time) *SyncMetaUpdateOne {
	_u.mutation.SetLastSync(v)
	return _u
}

// SetNillableLastSync sets the "last_sync" field if the given value is not nil.
func (_u *SyncMetaUpdateOne) SetNillableLastSync(v *time.Time) *SyncMetaUpdateOne {
	if v != nil {
		_u.SetLastSync(*v)
	}
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *SyncMetaUpdateOne) SetRecordCount(v int) *SyncMetaUpdateOne {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *SyncMetaUpdateOne) SetNillableRecordCount(v *int) *SyncMetaUpdateOne {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *SyncMetaUpdateOne) AddRecordCount(v int) *SyncMetaUpdateOne {
	_u.mutation.AddRecordCount(v)
	return _u
}

// ClearRecordCount clears the value of the "record_count" field.
func (_u *SyncMetaUpdateOne) ClearRecordCount() *SyncMetaUpdateOne {
	_u.mutation.ClearRecordCount()
	return _u
}

// Mutation returns the SyncMetaMutation object of the builder.
func (_u *SyncMetaUpdateOne) Mutation() *SyncMetaMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncMetaUpdate builder.
func (_u *SyncMetaUpdateOne) Where(ps ...predicate.SyncMeta) *SyncMetaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncMetaUpdateOne) Select(field string, fields ...string) *SyncMetaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncMeta entity.
func (_u *SyncMetaUpdateOne) Save(ctx context.Context) (*SyncMeta, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncMetaUpdateOne) SaveX(ctx context.Context) *SyncMeta {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncMetaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncMetaUpdateOne) sqlSave(ctx context.Context) (_node *SyncMeta, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncmeta.Table, syncmeta.Columns, sqlgraph.NewFieldSpec(syncmeta.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncmeta.FieldID)
		for _, f := range fields {
			if !syncmeta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncmeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Entity(); ok {
		_spec.SetField(syncmeta.FieldEntity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Product(); ok {
		_spec.SetField(syncmeta.FieldProduct, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSync(); ok {
		_spec.SetField(syncmeta.FieldLastSync, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(syncmeta.FieldRecordCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(syncmeta.FieldRecordCount, field.TypeInt, value)
	}
	if _u.mutation.RecordCountCleared() {
		_spec.ClearField(syncmeta.FieldRecordCount, field.TypeInt)
	}
	_node = &SyncMeta{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncmeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
