// Code generated by ent, DO NOT EDIT.

package syncmeta

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLTE(FieldID, id))
}

// Entity applies equality check predicate on the "entity" field. It's identical to EntityEQ.
func Entity(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldEntity, v))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldProduct, v))
}

// LastSync applies equality check predicate on the "last_sync" field. It's identical to LastSyncEQ.
func LastSync(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldLastSync, v))
}

// RecordCount applies equality check predicate on the "record_count" field. It's identical to RecordCountEQ.
func RecordCount(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldRecordCount, v))
}

// EntityEQ applies the EQ predicate on the "entity" field.
func EntityEQ(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldEntity, v))
}

// EntityNEQ applies the NEQ predicate on the "entity" field.
func EntityNEQ(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNEQ(FieldEntity, v))
}

// EntityIn applies the In predicate on the "entity" field.
func EntityIn(vs ...string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIn(FieldEntity, vs...))
}

// EntityNotIn applies the NotIn predicate on the "entity" field.
func EntityNotIn(vs ...string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotIn(FieldEntity, vs...))
}

// EntityGT applies the GT predicate on the "entity" field.
func EntityGT(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGT(FieldEntity, v))
}

// EntityGTE applies the GTE predicate on the "entity" field.
func EntityGTE(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGTE(FieldEntity, v))
}

// EntityLT applies the LT predicate on the "entity" field.
func EntityLT(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLT(FieldEntity, v))
}

// EntityLTE applies the LTE predicate on the "entity" field.
func EntityLTE(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLTE(FieldEntity, v))
}

// EntityContains applies the Contains predicate on the "entity" field.
func EntityContains(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldContains(FieldEntity, v))
}

// EntityHasPrefix applies the HasPrefix predicate on the "entity" field.
func EntityHasPrefix(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldHasPrefix(FieldEntity, v))
}

// EntityHasSuffix applies the HasSuffix predicate on the "entity" field.
func EntityHasSuffix(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldHasSuffix(FieldEntity, v))
}

// EntityEqualFold applies the EqualFold predicate on the "entity" field.
func EntityEqualFold(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEqualFold(FieldEntity, v))
}

// EntityContainsFold applies the ContainsFold predicate on the "entity" field.
func EntityContainsFold(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldContainsFold(FieldEntity, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldContainsFold(FieldProduct, v))
}

// LastSyncEQ applies the EQ predicate on the "last_sync" field.
func LastSyncEQ(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldLastSync, v))
}

// LastSyncNEQ applies the NEQ predicate on the "last_sync" field.
func LastSyncNEQ(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNEQ(FieldLastSync, v))
}

// LastSyncIn applies the In predicate on the "last_sync" field.
func LastSyncIn(vs ...time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIn(FieldLastSync, vs...))
}

// LastSyncNotIn applies the NotIn predicate on the "last_sync" field.
func LastSyncNotIn(vs ...time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotIn(FieldLastSync, vs...))
}

// LastSyncGT applies the GT predicate on the "last_sync" field.
func LastSyncGT(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGT(FieldLastSync, v))
}

// LastSyncGTE applies the GTE predicate on the "last_sync" field.
func LastSyncGTE(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGTE(FieldLastSync, v))
}

// LastSyncLT applies the LT predicate on the "last_sync" field.
func LastSyncLT(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLT(FieldLastSync, v))
}

// LastSyncLTE applies the LTE predicate on the "last_sync" field.
func LastSyncLTE(v time.Time) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLTE(FieldLastSync, v))
}

// RecordCountEQ applies the EQ predicate on the "record_count" field.
func RecordCountEQ(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldEQ(FieldRecordCount, v))
}

// RecordCountNEQ applies the NEQ predicate on the "record_count" field.
func RecordCountNEQ(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNEQ(FieldRecordCount, v))
}

// RecordCountIn applies the In predicate on the "record_count" field.
func RecordCountIn(vs ...int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIn(FieldRecordCount, vs...))
}

// RecordCountNotIn applies the NotIn predicate on the "record_count" field.
func RecordCountNotIn(vs ...int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotIn(FieldRecordCount, vs...))
}

// RecordCountGT applies the GT predicate on the "record_count" field.
func RecordCountGT(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGT(FieldRecordCount, v))
}

// RecordCountGTE applies the GTE predicate on the "record_count" field.
func RecordCountGTE(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldGTE(FieldRecordCount, v))
}

// RecordCountLT applies the LT predicate on the "record_count" field.
func RecordCountLT(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLT(FieldRecordCount, v))
}

// RecordCountLTE applies the LTE predicate on the "record_count" field.
func RecordCountLTE(v int) predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldLTE(FieldRecordCount, v))
}

// RecordCountIsNil applies the IsNil predicate on the "record_count" field.
func RecordCountIsNil() predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldIsNull(FieldRecordCount))
}

// RecordCountNotNil applies the NotNil predicate on the "record_count" field.
func RecordCountNotNil() predicate.SyncMeta {
	return predicate.SyncMeta(sql.FieldNotNull(FieldRecordCount))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncMeta) predicate.SyncMeta {
	return predicate.SyncMeta(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncMeta) predicate.SyncMeta {
	return predicate.SyncMeta(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncMeta) predicate.SyncMeta {
	return predicate.SyncMeta(sql.NotPredicates(p))
}
