// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/grokify/aha-studio/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldID, id))
}

// FromType applies equality check predicate on the "from_type" field. It's identical to FromTypeEQ.
func FromType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromType, v))
}

// FromID applies equality check predicate on the "from_id" field. It's identical to FromIDEQ.
func FromID(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromID, v))
}

// RelType applies equality check predicate on the "rel_type" field. It's identical to RelTypeEQ.
func RelType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldRelType, v))
}

// ToType applies equality check predicate on the "to_type" field. It's identical to ToTypeEQ.
func ToType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToType, v))
}

// ToID applies equality check predicate on the "to_id" field. It's identical to ToIDEQ.
func ToID(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToID, v))
}

// Product applies equality check predicate on the "product" field. It's identical to ProductEQ.
func Product(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldProduct, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// FromTypeEQ applies the EQ predicate on the "from_type" field.
func FromTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromType, v))
}

// FromTypeNEQ applies the NEQ predicate on the "from_type" field.
func FromTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldFromType, v))
}

// FromTypeIn applies the In predicate on the "from_type" field.
func FromTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldFromType, vs...))
}

// FromTypeNotIn applies the NotIn predicate on the "from_type" field.
func FromTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldFromType, vs...))
}

// FromTypeGT applies the GT predicate on the "from_type" field.
func FromTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldFromType, v))
}

// FromTypeGTE applies the GTE predicate on the "from_type" field.
func FromTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldFromType, v))
}

// FromTypeLT applies the LT predicate on the "from_type" field.
func FromTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldFromType, v))
}

// FromTypeLTE applies the LTE predicate on the "from_type" field.
func FromTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldFromType, v))
}

// FromTypeContains applies the Contains predicate on the "from_type" field.
func FromTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldFromType, v))
}

// FromTypeHasPrefix applies the HasPrefix predicate on the "from_type" field.
func FromTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldFromType, v))
}

// FromTypeHasSuffix applies the HasSuffix predicate on the "from_type" field.
func FromTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldFromType, v))
}

// FromTypeEqualFold applies the EqualFold predicate on the "from_type" field.
func FromTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldFromType, v))
}

// FromTypeContainsFold applies the ContainsFold predicate on the "from_type" field.
func FromTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldFromType, v))
}

// FromIDEQ applies the EQ predicate on the "from_id" field.
func FromIDEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromID, v))
}

// FromIDNEQ applies the NEQ predicate on the "from_id" field.
func FromIDNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldFromID, v))
}

// FromIDIn applies the In predicate on the "from_id" field.
func FromIDIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldFromID, vs...))
}

// FromIDNotIn applies the NotIn predicate on the "from_id" field.
func FromIDNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldFromID, vs...))
}

// FromIDGT applies the GT predicate on the "from_id" field.
func FromIDGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldFromID, v))
}

// FromIDGTE applies the GTE predicate on the "from_id" field.
func FromIDGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldFromID, v))
}

// FromIDLT applies the LT predicate on the "from_id" field.
func FromIDLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldFromID, v))
}

// FromIDLTE applies the LTE predicate on the "from_id" field.
func FromIDLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldFromID, v))
}

// FromIDContains applies the Contains predicate on the "from_id" field.
func FromIDContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldFromID, v))
}

// FromIDHasPrefix applies the HasPrefix predicate on the "from_id" field.
func FromIDHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldFromID, v))
}

// FromIDHasSuffix applies the HasSuffix predicate on the "from_id" field.
func FromIDHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldFromID, v))
}

// FromIDEqualFold applies the EqualFold predicate on the "from_id" field.
func FromIDEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldFromID, v))
}

// FromIDContainsFold applies the ContainsFold predicate on the "from_id" field.
func FromIDContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldFromID, v))
}

// RelTypeEQ applies the EQ predicate on the "rel_type" field.
func RelTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldRelType, v))
}

// RelTypeNEQ applies the NEQ predicate on the "rel_type" field.
func RelTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldRelType, v))
}

// RelTypeIn applies the In predicate on the "rel_type" field.
func RelTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldRelType, vs...))
}

// RelTypeNotIn applies the NotIn predicate on the "rel_type" field.
func RelTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldRelType, vs...))
}

// RelTypeGT applies the GT predicate on the "rel_type" field.
func RelTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldRelType, v))
}

// RelTypeGTE applies the GTE predicate on the "rel_type" field.
func RelTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldRelType, v))
}

// RelTypeLT applies the LT predicate on the "rel_type" field.
func RelTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldRelType, v))
}

// RelTypeLTE applies the LTE predicate on the "rel_type" field.
func RelTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldRelType, v))
}

// RelTypeContains applies the Contains predicate on the "rel_type" field.
func RelTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldRelType, v))
}

// RelTypeHasPrefix applies the HasPrefix predicate on the "rel_type" field.
func RelTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldRelType, v))
}

// RelTypeHasSuffix applies the HasSuffix predicate on the "rel_type" field.
func RelTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldRelType, v))
}

// RelTypeEqualFold applies the EqualFold predicate on the "rel_type" field.
func RelTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldRelType, v))
}

// RelTypeContainsFold applies the ContainsFold predicate on the "rel_type" field.
func RelTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldRelType, v))
}

// ToTypeEQ applies the EQ predicate on the "to_type" field.
func ToTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToType, v))
}

// ToTypeNEQ applies the NEQ predicate on the "to_type" field.
func ToTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldToType, v))
}

// ToTypeIn applies the In predicate on the "to_type" field.
func ToTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldToType, vs...))
}

// ToTypeNotIn applies the NotIn predicate on the "to_type" field.
func ToTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldToType, vs...))
}

// ToTypeGT applies the GT predicate on the "to_type" field.
func ToTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldToType, v))
}

// ToTypeGTE applies the GTE predicate on the "to_type" field.
func ToTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldToType, v))
}

// ToTypeLT applies the LT predicate on the "to_type" field.
func ToTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldToType, v))
}

// ToTypeLTE applies the LTE predicate on the "to_type" field.
func ToTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldToType, v))
}

// ToTypeContains applies the Contains predicate on the "to_type" field.
func ToTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldToType, v))
}

// ToTypeHasPrefix applies the HasPrefix predicate on the "to_type" field.
func ToTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldToType, v))
}

// ToTypeHasSuffix applies the HasSuffix predicate on the "to_type" field.
func ToTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldToType, v))
}

// ToTypeEqualFold applies the EqualFold predicate on the "to_type" field.
func ToTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldToType, v))
}

// ToTypeContainsFold applies the ContainsFold predicate on the "to_type" field.
func ToTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldToType, v))
}

// ToIDEQ applies the EQ predicate on the "to_id" field.
func ToIDEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToID, v))
}

// ToIDNEQ applies the NEQ predicate on the "to_id" field.
func ToIDNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldToID, v))
}

// ToIDIn applies the In predicate on the "to_id" field.
func ToIDIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldToID, vs...))
}

// ToIDNotIn applies the NotIn predicate on the "to_id" field.
func ToIDNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldToID, vs...))
}

// ToIDGT applies the GT predicate on the "to_id" field.
func ToIDGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldToID, v))
}

// ToIDGTE applies the GTE predicate on the "to_id" field.
func ToIDGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldToID, v))
}

// ToIDLT applies the LT predicate on the "to_id" field.
func ToIDLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldToID, v))
}

// ToIDLTE applies the LTE predicate on the "to_id" field.
func ToIDLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldToID, v))
}

// ToIDContains applies the Contains predicate on the "to_id" field.
func ToIDContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldToID, v))
}

// ToIDHasPrefix applies the HasPrefix predicate on the "to_id" field.
func ToIDHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldToID, v))
}

// ToIDHasSuffix applies the HasSuffix predicate on the "to_id" field.
func ToIDHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldToID, v))
}

// ToIDEqualFold applies the EqualFold predicate on the "to_id" field.
func ToIDEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldToID, v))
}

// ToIDContainsFold applies the ContainsFold predicate on the "to_id" field.
func ToIDContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldToID, v))
}

// ProductEQ applies the EQ predicate on the "product" field.
func ProductEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldProduct, v))
}

// ProductNEQ applies the NEQ predicate on the "product" field.
func ProductNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldProduct, v))
}

// ProductIn applies the In predicate on the "product" field.
func ProductIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldProduct, vs...))
}

// ProductNotIn applies the NotIn predicate on the "product" field.
func ProductNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldProduct, vs...))
}

// ProductGT applies the GT predicate on the "product" field.
func ProductGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldProduct, v))
}

// ProductGTE applies the GTE predicate on the "product" field.
func ProductGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldProduct, v))
}

// ProductLT applies the LT predicate on the "product" field.
func ProductLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldProduct, v))
}

// ProductLTE applies the LTE predicate on the "product" field.
func ProductLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldProduct, v))
}

// ProductContains applies the Contains predicate on the "product" field.
func ProductContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldProduct, v))
}

// ProductHasPrefix applies the HasPrefix predicate on the "product" field.
func ProductHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldProduct, v))
}

// ProductHasSuffix applies the HasSuffix predicate on the "product" field.
func ProductHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldProduct, v))
}

// ProductIsNil applies the IsNil predicate on the "product" field.
func ProductIsNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldIsNull(FieldProduct))
}

// ProductNotNil applies the NotNil predicate on the "product" field.
func ProductNotNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldNotNull(FieldProduct))
}

// ProductEqualFold applies the EqualFold predicate on the "product" field.
func ProductEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldProduct, v))
}

// ProductContainsFold applies the ContainsFold predicate on the "product" field.
func ProductContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldProduct, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.NotPredicates(p))
}
